mydata = read.table('/Data/Training/QSMART/autonomic_ganglia.csv',head=T,sep=",")
model = lm(IC50 ~ factor(Cancer) + factor(Drug), data=mydata)
sse <- c(crossprod(model$residuals))
sink('/Data/Model/ANOVA/autonomic_ganglia.txt',append=TRUE)
print(summary(model))
print(sse)
sink()
