mydata = read.table('./TrainingSet/AvgRank/oesophagus.csv',head=T,sep=",")
model = lm(IC50 ~ factor(Cancer) + factor(Drug), data=mydata)
sse <- c(crossprod(model$residuals))
sink('./Model/ANOVA/oesophagus.txt',append=TRUE)
print(summary(model))
print(sse)
sink()
