library(glmnet)
mydata = read.table("./TrainingSet/LassoBIC/central_nervous_system.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0.95,family="gaussian",standardize=TRUE)
sink('./Model/EN/Lasso/central_nervous_system/central_nervous_system_095.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
