from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """

def getModelMetadata():
	return {"creator": u"Neural", "modelName": u"", "predicted": u"IC50", "table": u"cervix", "version": u"14.1.0", "timestamp": u"2019-07-30T15:51:38Z"}


def getInputMetadata():
    return {
        u"Fingerprint_363": "float",
        u"Fingerprint_588": "float",
        u"Fingerprint_611": "float",
        u"Fingerprint_617": "float",
        u"Fingerprint_629": "float",
        u"Fingerprint_635": "float",
        u"Fingerprint_643": "float",
        u"Fingerprint_644": "float",
        u"Fingerprint_646": "float",
        u"Fingerprint_667": "float",
        u"Fingerprint_673": "float",
        u"Fingerprint_677": "float",
        u"Fingerprint_685": "float",
        u"Fingerprint_686": "float",
        u"Fingerprint_697": "float",
        u"Fingerprint_710": "float",
        u"Fingerprint_714": "float",
        u"Fingerprint_776": "float",
        u"Fingerprint_791": "float",
        u"Fingerprint_797": "float",
        u"Fingerprint_813": "float",
        u"Fingerprint_818": "float",
        u"Fingerprint_819": "float",
        u"Fingerprint_820": "float",
        u"Fingerprint_821": "float",
        u"Fingerprint_822": "float",
        u"Fingerprint_824": "float",
        u"Fingerprint_826": "float",
        u"From_Sanger": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6
    # H1_7

    H1_1 = tanh((0.0767458177250206 + -4.40470995428532 * indata[u"Fingerprint_363"] + -6.31217041969221 * indata[u"Fingerprint_588"] + 6.4664701010514 * indata[u"Fingerprint_611"] + 1.37467887662802 * indata[u"Fingerprint_617"] + -1.81339584912673 * indata[u"Fingerprint_629"] + 2.72862942780798 * indata[u"Fingerprint_635"] + -2.73904412837057 * indata[u"Fingerprint_643"] + 9.7955717047858 * indata[u"Fingerprint_644"] + 8.95405886578657 * indata[u"Fingerprint_646"] + 6.98125415080167 * indata[u"Fingerprint_667"] + -6.75177113044255 * indata[u"Fingerprint_673"] + -1.36064606463385 * indata[u"Fingerprint_677"] + -5.31173290914561 * indata[u"Fingerprint_685"] + 17.4189436757641 * indata[u"Fingerprint_686"] + -5.32376342381858 * indata[u"Fingerprint_697"] + -2.54723357894481 * indata[u"Fingerprint_710"] + 2.33161514037923 * indata[u"Fingerprint_714"] + 10.3608556693165 * indata[u"Fingerprint_776"] + 1.99765994677247 * indata[u"Fingerprint_791"] + -9.57992931550212 * indata[u"Fingerprint_797"] + 9.3686561430875 * indata[u"Fingerprint_813"] + -7.11149998121864 * indata[u"Fingerprint_818"] + -1.12468243659061 * indata[u"Fingerprint_819"] + 0.353531080943803 * indata[u"Fingerprint_820"] + 2.10932152134526 * indata[u"Fingerprint_821"] + 11.5215907403802 * indata[u"Fingerprint_822"] + 0.674987371723823 * indata[u"Fingerprint_824"] + 9.37910257192173 * indata[u"Fingerprint_826"] + 0.831235630811628 * indata[u"From_Sanger"]))

    H1_2 = tanh((0.239553608617215 + -4.02588553940743 * indata[u"Fingerprint_363"] + -1.18293749057594 * indata[u"Fingerprint_588"] + 0.0582985966600502 * indata[u"Fingerprint_611"] + 4.38371426815073 * indata[u"Fingerprint_617"] + -1.66811555681677 * indata[u"Fingerprint_629"] + -11.74572590545 * indata[u"Fingerprint_635"] + 0.451611646889417 * indata[u"Fingerprint_643"] + -6.17068504583929 * indata[u"Fingerprint_644"] + -0.0572306460112983 * indata[u"Fingerprint_646"] + 11.2525811997263 * indata[u"Fingerprint_667"] + 5.05663130895077 * indata[u"Fingerprint_673"] + 6.33796522480659 * indata[u"Fingerprint_677"] + 5.28887298075994 * indata[u"Fingerprint_685"] + -3.55881735757178 * indata[u"Fingerprint_686"] + 2.13579236101407 * indata[u"Fingerprint_697"] + -0.98332020502231 * indata[u"Fingerprint_710"] + 0.12872547491544 * indata[u"Fingerprint_714"] + -6.53405449787407 * indata[u"Fingerprint_776"] + 11.3204973047809 * indata[u"Fingerprint_791"] + -2.16725311394594 * indata[u"Fingerprint_797"] + -9.35291576963973 * indata[u"Fingerprint_813"] + 0.978420528357971 * indata[u"Fingerprint_818"] + 7.05262244065889 * indata[u"Fingerprint_819"] + -8.3527480318513 * indata[u"Fingerprint_820"] + -4.63318078390172 * indata[u"Fingerprint_821"] + -4.41742074854351 * indata[u"Fingerprint_822"] + -2.3784242756709 * indata[u"Fingerprint_824"] + -9.92911217292142 * indata[u"Fingerprint_826"] + -1.20918384538827 * indata[u"From_Sanger"]))

    H1_3 = tanh((-2.10709714767254 + 12.5905230577708 * indata[u"Fingerprint_363"] + -4.53606338538545 * indata[u"Fingerprint_588"] + -5.19140263685576 * indata[u"Fingerprint_611"] + -2.49261571587505 * indata[u"Fingerprint_617"] + 3.66824857622066 * indata[u"Fingerprint_629"] + 3.95160912620724 * indata[u"Fingerprint_635"] + 5.69148093962093 * indata[u"Fingerprint_643"] + -1.81500309267067 * indata[u"Fingerprint_644"] + 4.40497386532599 * indata[u"Fingerprint_646"] + 8.76683526718677 * indata[u"Fingerprint_667"] + 1.46365652129713 * indata[u"Fingerprint_673"] + -2.5680724925008 * indata[u"Fingerprint_677"] + -2.34085096810956 * indata[u"Fingerprint_685"] + 0.198330307744248 * indata[u"Fingerprint_686"] + 1.9909173400318 * indata[u"Fingerprint_697"] + -5.76354750002833 * indata[u"Fingerprint_710"] + 0.410402867166399 * indata[u"Fingerprint_714"] + -4.55564675115037 * indata[u"Fingerprint_776"] + 3.87534439358907 * indata[u"Fingerprint_791"] + 3.41298050732979 * indata[u"Fingerprint_797"] + 2.26642005130026 * indata[u"Fingerprint_813"] + 6.13832257217337 * indata[u"Fingerprint_818"] + -3.44307655288744 * indata[u"Fingerprint_819"] + 1.50414614942132 * indata[u"Fingerprint_820"] + 5.68232116237302 * indata[u"Fingerprint_821"] + 12.4080299231552 * indata[u"Fingerprint_822"] + 7.34079067535273 * indata[u"Fingerprint_824"] + -0.782973046618809 * indata[u"Fingerprint_826"] + 4.83043424168642 * indata[u"From_Sanger"]))

    H1_4 = tanh((-6.21452859449491 + -12.9555403488979 * indata[u"Fingerprint_363"] + -20.1392104928895 * indata[u"Fingerprint_588"] + -1.12032168843931 * indata[u"Fingerprint_611"] + 9.54152196479819 * indata[u"Fingerprint_617"] + -5.09864780955787 * indata[u"Fingerprint_629"] + -1.59603079038657 * indata[u"Fingerprint_635"] + 1.86182038860366 * indata[u"Fingerprint_643"] + 1.72982235477409 * indata[u"Fingerprint_644"] + 15.6577210281052 * indata[u"Fingerprint_646"] + -7.52484781049958 * indata[u"Fingerprint_667"] + -2.12686268278014 * indata[u"Fingerprint_673"] + 5.52136890071439 * indata[u"Fingerprint_677"] + -9.2653126823398 * indata[u"Fingerprint_685"] + 2.37359847869648 * indata[u"Fingerprint_686"] + -4.9170949098998 * indata[u"Fingerprint_697"] + 4.26502021503527 * indata[u"Fingerprint_710"] + -2.79193634359518 * indata[u"Fingerprint_714"] + -2.18306029115143 * indata[u"Fingerprint_776"] + 1.55531199221667 * indata[u"Fingerprint_791"] + -0.0255974311768076 * indata[u"Fingerprint_797"] + 6.55364978129673 * indata[u"Fingerprint_813"] + 1.24529995035617 * indata[u"Fingerprint_818"] + 10.7000225257582 * indata[u"Fingerprint_819"] + 8.75236161344646 * indata[u"Fingerprint_820"] + -2.16206672863092 * indata[u"Fingerprint_821"] + -1.6386475816209 * indata[u"Fingerprint_822"] + -8.95122811487432 * indata[u"Fingerprint_824"] + 8.29705248306714 * indata[u"Fingerprint_826"] + -0.908032127722117 * indata[u"From_Sanger"]))

    H1_5 = tanh((2.61980619404341 + 10.6935224262091 * indata[u"Fingerprint_363"] + 1.65335801376776 * indata[u"Fingerprint_588"] + -3.53501079261565 * indata[u"Fingerprint_611"] + -1.81261980798478 * indata[u"Fingerprint_617"] + -10.3835104093028 * indata[u"Fingerprint_629"] + -2.72384591467587 * indata[u"Fingerprint_635"] + 3.429747050214 * indata[u"Fingerprint_643"] + -1.34602061231171 * indata[u"Fingerprint_644"] + -3.58842208415997 * indata[u"Fingerprint_646"] + -5.58351469089809 * indata[u"Fingerprint_667"] + -5.18092063214028 * indata[u"Fingerprint_673"] + -4.03573129577881 * indata[u"Fingerprint_677"] + 5.35781322698266 * indata[u"Fingerprint_685"] + 1.07939648528601 * indata[u"Fingerprint_686"] + -2.20497643572074 * indata[u"Fingerprint_697"] + 8.90442558723511 * indata[u"Fingerprint_710"] + -4.19914629832093 * indata[u"Fingerprint_714"] + 0.84870451393739 * indata[u"Fingerprint_776"] + -10.3522718556026 * indata[u"Fingerprint_791"] + 2.23624846609245 * indata[u"Fingerprint_797"] + -7.29667204343612 * indata[u"Fingerprint_813"] + -0.283213820920747 * indata[u"Fingerprint_818"] + 3.54942547581442 * indata[u"Fingerprint_819"] + 4.82477757280701 * indata[u"Fingerprint_820"] + -4.00629344990736 * indata[u"Fingerprint_821"] + -6.78622667562106 * indata[u"Fingerprint_822"] + 2.01286649754325 * indata[u"Fingerprint_824"] + 1.44392544500098 * indata[u"Fingerprint_826"] + 0.218200677222205 * indata[u"From_Sanger"]))

    H1_6 = tanh((-11.1266134528497 + 0.827191099817006 * indata[u"Fingerprint_363"] + 3.68311939006966 * indata[u"Fingerprint_588"] + 1.99522258708986 * indata[u"Fingerprint_611"] + 9.26491154232813 * indata[u"Fingerprint_617"] + 0.647562548565043 * indata[u"Fingerprint_629"] + -6.98201822998438 * indata[u"Fingerprint_635"] + 6.23564635050918 * indata[u"Fingerprint_643"] + 0.0167873518603716 * indata[u"Fingerprint_644"] + -6.15461866162077 * indata[u"Fingerprint_646"] + -0.546973603619362 * indata[u"Fingerprint_667"] + -1.9687030620595 * indata[u"Fingerprint_673"] + -2.29623470065915 * indata[u"Fingerprint_677"] + 9.42030151751774 * indata[u"Fingerprint_685"] + 5.95492065993942 * indata[u"Fingerprint_686"] + -3.09953853561473 * indata[u"Fingerprint_697"] + 0.259991509650108 * indata[u"Fingerprint_710"] + 2.02745176276545 * indata[u"Fingerprint_714"] + -2.84109759119186 * indata[u"Fingerprint_776"] + -1.81673054895826 * indata[u"Fingerprint_791"] + 5.22101162453493 * indata[u"Fingerprint_797"] + 4.03845168544313 * indata[u"Fingerprint_813"] + 8.31876721970635 * indata[u"Fingerprint_818"] + 0.685667728950137 * indata[u"Fingerprint_819"] + -8.66726583351614 * indata[u"Fingerprint_820"] + 4.37156790429729 * indata[u"Fingerprint_821"] + 11.8633428004516 * indata[u"Fingerprint_822"] + 6.16496493631465 * indata[u"Fingerprint_824"] + -8.60022163257147 * indata[u"Fingerprint_826"] + 0.248582776232685 * indata[u"From_Sanger"]))

    H1_7 = tanh((-9.48481574234404 + 5.77195770783182 * indata[u"Fingerprint_363"] + -7.30889183701779 * indata[u"Fingerprint_588"] + 2.46688957903357 * indata[u"Fingerprint_611"] + -3.24997692528856 * indata[u"Fingerprint_617"] + 1.77307829528766 * indata[u"Fingerprint_629"] + -10.3584389435851 * indata[u"Fingerprint_635"] + 2.07385675753142 * indata[u"Fingerprint_643"] + 0.0937043787349624 * indata[u"Fingerprint_644"] + 1.65001999784807 * indata[u"Fingerprint_646"] + 0.159685717447476 * indata[u"Fingerprint_667"] + -1.9355669529361 * indata[u"Fingerprint_673"] + -0.96241629225288 * indata[u"Fingerprint_677"] + -0.00464081823447381 * indata[u"Fingerprint_685"] + -6.77266657119677 * indata[u"Fingerprint_686"] + -0.617522290782672 * indata[u"Fingerprint_697"] + 0.524961429451471 * indata[u"Fingerprint_710"] + 1.78208888421259 * indata[u"Fingerprint_714"] + -0.392492671984497 * indata[u"Fingerprint_776"] + 11.3229519051693 * indata[u"Fingerprint_791"] + 3.88464929150646 * indata[u"Fingerprint_797"] + -14.6478570043672 * indata[u"Fingerprint_813"] + -3.48591548431555 * indata[u"Fingerprint_818"] + -14.5180032856732 * indata[u"Fingerprint_819"] + -17.0050491718167 * indata[u"Fingerprint_820"] + 2.58571460970627 * indata[u"Fingerprint_821"] + -26.0474234747715 * indata[u"Fingerprint_822"] + 6.06032145791115 * indata[u"Fingerprint_824"] + -5.58329794570876 * indata[u"Fingerprint_826"] + 12.230051327343 * indata[u"From_Sanger"]))

    outdata[u"Predicted IC50_1"] = 1.24712184541576 + 1.6748938420729 * H1_1 + 1.24206500286811 * H1_2 + 0.902750929704786 * H1_3 + -1.32381405621394 * H1_4 + 1.49932828341442 * H1_5 + -1.13280304576775 * H1_6 + -1.21567190270497 * H1_7

    return outdata[u"Predicted IC50_1"]


