from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """

def getModelMetadata():
	return {"creator": u"Neural", "modelName": u"", "predicted": u"IC50", "table": u"liver", "version": u"14.1.0", "timestamp": u"2019-07-26T18:42:37Z"}


def getInputMetadata():
    return {
        u"Fingerprint_363": "float",
        u"Fingerprint_611": "float",
        u"Fingerprint_617": "float",
        u"Fingerprint_629": "float",
        u"Fingerprint_635": "float",
        u"Fingerprint_644": "float",
        u"Fingerprint_646": "float",
        u"Fingerprint_658": "float",
        u"Fingerprint_659": "float",
        u"Fingerprint_667": "float",
        u"Fingerprint_672": "float",
        u"Fingerprint_673": "float",
        u"Fingerprint_674": "float",
        u"Fingerprint_677": "float",
        u"Fingerprint_685": "float",
        u"Fingerprint_686": "float",
        u"Fingerprint_697": "float",
        u"Fingerprint_698": "float",
        u"Fingerprint_709": "float",
        u"Fingerprint_710": "float",
        u"Fingerprint_712": "float",
        u"Fingerprint_714": "float",
        u"Fingerprint_776": "float",
        u"Fingerprint_791": "float",
        u"Fingerprint_797": "float",
        u"Fingerprint_813": "float",
        u"Fingerprint_818": "float",
        u"Fingerprint_819": "float",
        u"Fingerprint_820": "float",
        u"Fingerprint_821": "float",
        u"Fingerprint_822": "float",
        u"Fingerprint_826": "float",
        u"Fingerprint_830": "float",
        u"Fingerprint_834": "float",
        u"From_Sanger": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6
    # H1_7

    H1_1 = tanh((16.7856592044184 + -0.961007226850701 * indata[u"Fingerprint_363"] + -3.80834354941692 * indata[u"Fingerprint_611"] + -0.382332799162704 * indata[u"Fingerprint_617"] + -2.74746027234211 * indata[u"Fingerprint_629"] + -3.66822543598393 * indata[u"Fingerprint_635"] + -0.948803664837141 * indata[u"Fingerprint_644"] + -0.618633614830911 * indata[u"Fingerprint_646"] + 2.91410867979877 * indata[u"Fingerprint_658"] + -0.331880390696462 * indata[u"Fingerprint_659"] + -4.9307813462648 * indata[u"Fingerprint_667"] + 0.962647861405133 * indata[u"Fingerprint_672"] + 0.102293081000301 * indata[u"Fingerprint_673"] + 0.549725995476708 * indata[u"Fingerprint_674"] + -11.7627056196209 * indata[u"Fingerprint_677"] + 0.628155226529948 * indata[u"Fingerprint_685"] + 1.03259578584309 * indata[u"Fingerprint_686"] + 3.31032093524211 * indata[u"Fingerprint_697"] + 0.867856112646635 * indata[u"Fingerprint_698"] + 2.40631190278583 * indata[u"Fingerprint_709"] + -4.44270129996599 * indata[u"Fingerprint_710"] + -0.289809210476649 * indata[u"Fingerprint_712"] + 5.30106841264993 * indata[u"Fingerprint_714"] + 1.41191751641744 * indata[u"Fingerprint_776"] + -6.22241637381644 * indata[u"Fingerprint_791"] + -4.84660243485164 * indata[u"Fingerprint_797"] + 0.88187027282659 * indata[u"Fingerprint_813"] + -3.78665153759474 * indata[u"Fingerprint_818"] + 0.824366326998501 * indata[u"Fingerprint_819"] + 3.76092324449684 * indata[u"Fingerprint_820"] + 2.24799090986204 * indata[u"Fingerprint_821"] + 1.43890350294989 * indata[u"Fingerprint_822"] + -2.60515314233473 * indata[u"Fingerprint_826"] + 6.71667797905959 * indata[u"Fingerprint_830"] + 4.09939322714604 * indata[u"Fingerprint_834"] + -9.51728047294173 * indata[u"From_Sanger"]))

    H1_2 = tanh((1.49351949476032 + -3.66649734611125 * indata[u"Fingerprint_363"] + 0.523421182218527 * indata[u"Fingerprint_611"] + -0.421718401152094 * indata[u"Fingerprint_617"] + -4.16503628946766 * indata[u"Fingerprint_629"] + -1.24351721984012 * indata[u"Fingerprint_635"] + -2.52940546137473 * indata[u"Fingerprint_644"] + -2.07984642540006 * indata[u"Fingerprint_646"] + -0.924204885958749 * indata[u"Fingerprint_658"] + 1.69107432804326 * indata[u"Fingerprint_659"] + 6.02325936767473 * indata[u"Fingerprint_667"] + 1.55085871837056 * indata[u"Fingerprint_672"] + -1.95389897831697 * indata[u"Fingerprint_673"] + 2.60667019933015 * indata[u"Fingerprint_674"] + 2.66237651713486 * indata[u"Fingerprint_677"] + -3.64832133135783 * indata[u"Fingerprint_685"] + -3.15493788708406 * indata[u"Fingerprint_686"] + -0.609994399627496 * indata[u"Fingerprint_697"] + -3.09302350694103 * indata[u"Fingerprint_698"] + -5.34497597678092 * indata[u"Fingerprint_709"] + 4.8465999612724 * indata[u"Fingerprint_710"] + -1.12829637888674 * indata[u"Fingerprint_712"] + -1.38182719856685 * indata[u"Fingerprint_714"] + -4.00526083712886 * indata[u"Fingerprint_776"] + 2.60871535990431 * indata[u"Fingerprint_791"] + 0.356820672289827 * indata[u"Fingerprint_797"] + -3.20110625918337 * indata[u"Fingerprint_813"] + -0.0607817636627091 * indata[u"Fingerprint_818"] + 5.65632718377154 * indata[u"Fingerprint_819"] + 1.28862021074786 * indata[u"Fingerprint_820"] + -4.21277291413693 * indata[u"Fingerprint_821"] + -0.0790369862002212 * indata[u"Fingerprint_822"] + -0.902798546758343 * indata[u"Fingerprint_826"] + 2.96767862615639 * indata[u"Fingerprint_830"] + 1.45232751583896 * indata[u"Fingerprint_834"] + -0.30118027319864 * indata[u"From_Sanger"]))

    H1_3 = tanh((-12.7226163007224 + -1.97967661000774 * indata[u"Fingerprint_363"] + -1.77286863825613 * indata[u"Fingerprint_611"] + -2.35683597017665 * indata[u"Fingerprint_617"] + -0.123018278474583 * indata[u"Fingerprint_629"] + 2.50867835034304 * indata[u"Fingerprint_635"] + 2.16884483222666 * indata[u"Fingerprint_644"] + 1.74765103991167 * indata[u"Fingerprint_646"] + 1.74286517162341 * indata[u"Fingerprint_658"] + 3.86022696588355 * indata[u"Fingerprint_659"] + -7.20426683367942 * indata[u"Fingerprint_667"] + 0.748850379966189 * indata[u"Fingerprint_672"] + 2.877401564315 * indata[u"Fingerprint_673"] + 2.60149636195887 * indata[u"Fingerprint_674"] + 5.98138680201501 * indata[u"Fingerprint_677"] + -3.4470373932464 * indata[u"Fingerprint_685"] + 0.0292965863873138 * indata[u"Fingerprint_686"] + -4.00578678418065 * indata[u"Fingerprint_697"] + -0.232935156187274 * indata[u"Fingerprint_698"] + 2.94037515558748 * indata[u"Fingerprint_709"] + 2.18691184365418 * indata[u"Fingerprint_710"] + 2.10159606854279 * indata[u"Fingerprint_712"] + -0.683833349817757 * indata[u"Fingerprint_714"] + 2.53174313279967 * indata[u"Fingerprint_776"] + -0.471782724206806 * indata[u"Fingerprint_791"] + 2.69660610421107 * indata[u"Fingerprint_797"] + -1.14633479869937 * indata[u"Fingerprint_813"] + -3.69783254294271 * indata[u"Fingerprint_818"] + -5.92050064091236 * indata[u"Fingerprint_819"] + 2.56798913043097 * indata[u"Fingerprint_820"] + 0.736924143417776 * indata[u"Fingerprint_821"] + 0.292030942897205 * indata[u"Fingerprint_822"] + -8.04341840443007 * indata[u"Fingerprint_826"] + 3.07415384459968 * indata[u"Fingerprint_830"] + 0.184649168759875 * indata[u"Fingerprint_834"] + -2.58961597282536 * indata[u"From_Sanger"]))

    H1_4 = tanh((-18.5703808901463 + 0.735042600842885 * indata[u"Fingerprint_363"] + 3.16041067597094 * indata[u"Fingerprint_611"] + 1.66009617734347 * indata[u"Fingerprint_617"] + 4.59084999126954 * indata[u"Fingerprint_629"] + -11.5720777007433 * indata[u"Fingerprint_635"] + 0.461026469095734 * indata[u"Fingerprint_644"] + -0.78873887021876 * indata[u"Fingerprint_646"] + -4.09481489594673 * indata[u"Fingerprint_658"] + 3.95655404908291 * indata[u"Fingerprint_659"] + -0.540877062011238 * indata[u"Fingerprint_667"] + -0.661377897972781 * indata[u"Fingerprint_672"] + -2.91963952837388 * indata[u"Fingerprint_673"] + 5.33521061130383 * indata[u"Fingerprint_674"] + 15.9611067285802 * indata[u"Fingerprint_677"] + -5.53782968158321 * indata[u"Fingerprint_685"] + -7.81227140924684 * indata[u"Fingerprint_686"] + -1.73106712486524 * indata[u"Fingerprint_697"] + 2.4304221345347 * indata[u"Fingerprint_698"] + 2.05531469229867 * indata[u"Fingerprint_709"] + -3.70554143509741 * indata[u"Fingerprint_710"] + -0.749292987630359 * indata[u"Fingerprint_712"] + 1.95584615113451 * indata[u"Fingerprint_714"] + -3.01012007595918 * indata[u"Fingerprint_776"] + 0.864437974673239 * indata[u"Fingerprint_791"] + 5.65694145286256 * indata[u"Fingerprint_797"] + -8.93671227113674 * indata[u"Fingerprint_813"] + 7.64655973454093 * indata[u"Fingerprint_818"] + -3.68153193497263 * indata[u"Fingerprint_819"] + -0.94658512162429 * indata[u"Fingerprint_820"] + -2.12523690626518 * indata[u"Fingerprint_821"] + -7.59397754678004 * indata[u"Fingerprint_822"] + -2.33725059072691 * indata[u"Fingerprint_826"] + -8.73037978487334 * indata[u"Fingerprint_830"] + 4.95591561707478 * indata[u"Fingerprint_834"] + 1.33730096340248 * indata[u"From_Sanger"]))

    H1_5 = tanh((-5.11437477089372 + 2.73600459154614 * indata[u"Fingerprint_363"] + -1.64817668757454 * indata[u"Fingerprint_611"] + -6.9488619750166 * indata[u"Fingerprint_617"] + 0.225072188684203 * indata[u"Fingerprint_629"] + 2.35248904973025 * indata[u"Fingerprint_635"] + -1.04875965368491 * indata[u"Fingerprint_644"] + 2.43121207738124 * indata[u"Fingerprint_646"] + -1.57720857705964 * indata[u"Fingerprint_658"] + 2.78875232379024 * indata[u"Fingerprint_659"] + -3.2014843895753 * indata[u"Fingerprint_667"] + 0.428907019671898 * indata[u"Fingerprint_672"] + 0.0950575148815172 * indata[u"Fingerprint_673"] + -5.27527317503577 * indata[u"Fingerprint_674"] + 5.65637284310717 * indata[u"Fingerprint_677"] + -0.897711993577471 * indata[u"Fingerprint_685"] + -1.32340241415091 * indata[u"Fingerprint_686"] + 0.539237465121407 * indata[u"Fingerprint_697"] + 1.0836056642752 * indata[u"Fingerprint_698"] + -4.53247167341103 * indata[u"Fingerprint_709"] + 5.29746700989828 * indata[u"Fingerprint_710"] + 0.0107745891212197 * indata[u"Fingerprint_712"] + 1.9586057980693 * indata[u"Fingerprint_714"] + 1.84388261518072 * indata[u"Fingerprint_776"] + -1.63027964261396 * indata[u"Fingerprint_791"] + -2.54946700353299 * indata[u"Fingerprint_797"] + 5.22769497495565 * indata[u"Fingerprint_813"] + 0.0777753792218017 * indata[u"Fingerprint_818"] + 2.19740242427543 * indata[u"Fingerprint_819"] + -0.872837683702343 * indata[u"Fingerprint_820"] + -0.0450088802692553 * indata[u"Fingerprint_821"] + 8.94968710096228 * indata[u"Fingerprint_822"] + -1.53708418374067 * indata[u"Fingerprint_826"] + 5.85954519617699 * indata[u"Fingerprint_830"] + 4.56065544485364 * indata[u"Fingerprint_834"] + 3.34209336020105 * indata[u"From_Sanger"]))

    H1_6 = tanh((3.52172222564262 + -5.54779779380446 * indata[u"Fingerprint_363"] + -2.56557392749227 * indata[u"Fingerprint_611"] + -0.484965803285689 * indata[u"Fingerprint_617"] + 2.6224792180226 * indata[u"Fingerprint_629"] + 1.98904593317936 * indata[u"Fingerprint_635"] + -2.66867679713173 * indata[u"Fingerprint_644"] + -2.66551725922105 * indata[u"Fingerprint_646"] + -1.27097689298876 * indata[u"Fingerprint_658"] + -0.569284869960916 * indata[u"Fingerprint_659"] + 2.68898028080895 * indata[u"Fingerprint_667"] + -1.24998417271197 * indata[u"Fingerprint_672"] + 3.28330223051989 * indata[u"Fingerprint_673"] + -2.27553933654569 * indata[u"Fingerprint_674"] + -4.13659221405016 * indata[u"Fingerprint_677"] + 3.50483670522141 * indata[u"Fingerprint_685"] + -2.54899634163212 * indata[u"Fingerprint_686"] + 3.06602341914688 * indata[u"Fingerprint_697"] + 1.17156067603125 * indata[u"Fingerprint_698"] + 4.46356619680011 * indata[u"Fingerprint_709"] + 0.658533242661774 * indata[u"Fingerprint_710"] + -1.74092148829978 * indata[u"Fingerprint_712"] + -0.00192337690684219 * indata[u"Fingerprint_714"] + -2.02792126002656 * indata[u"Fingerprint_776"] + 1.60166895860437 * indata[u"Fingerprint_791"] + -3.75983535962341 * indata[u"Fingerprint_797"] + 2.19125340808326 * indata[u"Fingerprint_813"] + -4.13412574627235 * indata[u"Fingerprint_818"] + -0.37658651668985 * indata[u"Fingerprint_819"] + -0.990063216155028 * indata[u"Fingerprint_820"] + -1.80233416701097 * indata[u"Fingerprint_821"] + 0.24690532552197 * indata[u"Fingerprint_822"] + -5.14652060973316 * indata[u"Fingerprint_826"] + 5.82349365681471 * indata[u"Fingerprint_830"] + 0.156026277468462 * indata[u"Fingerprint_834"] + -0.90307023287752 * indata[u"From_Sanger"]))

    H1_7 = tanh((-3.01612821569485 + 0.569744899904638 * indata[u"Fingerprint_363"] + -1.51283201421901 * indata[u"Fingerprint_611"] + -3.15451987129425 * indata[u"Fingerprint_617"] + 2.80537620368291 * indata[u"Fingerprint_629"] + 5.67142127513427 * indata[u"Fingerprint_635"] + 1.05717092626744 * indata[u"Fingerprint_644"] + -1.659785519874 * indata[u"Fingerprint_646"] + -0.348923683081851 * indata[u"Fingerprint_658"] + -0.624555255957099 * indata[u"Fingerprint_659"] + 3.71578898963817 * indata[u"Fingerprint_667"] + -0.302333657824945 * indata[u"Fingerprint_672"] + -0.3066438193299 * indata[u"Fingerprint_673"] + 0.254201465588398 * indata[u"Fingerprint_674"] + -0.787365522232115 * indata[u"Fingerprint_677"] + 3.78645442178605 * indata[u"Fingerprint_685"] + 0.820308056009391 * indata[u"Fingerprint_686"] + 0.425111279203935 * indata[u"Fingerprint_697"] + -0.856245790706906 * indata[u"Fingerprint_698"] + 9.17417860624001 * indata[u"Fingerprint_709"] + -0.541762269847445 * indata[u"Fingerprint_710"] + -0.50229804765821 * indata[u"Fingerprint_712"] + -1.72772944613722 * indata[u"Fingerprint_714"] + 1.20444549914777 * indata[u"Fingerprint_776"] + 5.39926682487085 * indata[u"Fingerprint_791"] + -2.01909607679052 * indata[u"Fingerprint_797"] + -8.52954858363391 * indata[u"Fingerprint_813"] + -2.48298141577002 * indata[u"Fingerprint_818"] + -2.47268332751541 * indata[u"Fingerprint_819"] + 0.434413414335157 * indata[u"Fingerprint_820"] + -3.22748412030796 * indata[u"Fingerprint_821"] + 1.92339919888432 * indata[u"Fingerprint_822"] + 1.64357879607543 * indata[u"Fingerprint_826"] + -7.46038185514888 * indata[u"Fingerprint_830"] + -6.45527703433774 * indata[u"Fingerprint_834"] + 1.69625230138169 * indata[u"From_Sanger"]))

    outdata[u"Predicted IC50_1"] = 1.68848339927961 + 1.6962913216623 * H1_1 + 0.842908023508984 * H1_2 + -0.892314893110131 * H1_3 + -0.230515977226476 * H1_4 + 0.899734600987814 * H1_5 + -0.689530386350562 * H1_6 + 1.40676282589374 * H1_7

    return outdata[u"Predicted IC50_1"]


