from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """


def getInputMetadata():
    return {
        u"Fingerprint_576": "float",
        u"Fingerprint_611": "float",
        u"Fingerprint_617": "float",
        u"Fingerprint_635": "float",
        u"Fingerprint_643": "float",
        u"Fingerprint_644": "float",
        u"Fingerprint_647": "float",
        u"Fingerprint_650": "float",
        u"Fingerprint_658": "float",
        u"Fingerprint_659": "float",
        u"Fingerprint_667": "float",
        u"Fingerprint_673": "float",
        u"Fingerprint_685": "float",
        u"Fingerprint_686": "float",
        u"Fingerprint_696": "float",
        u"Fingerprint_698": "float",
        u"Fingerprint_702": "float",
        u"Fingerprint_704": "float",
        u"Fingerprint_707": "float",
        u"Fingerprint_711": "float",
        u"Fingerprint_712": "float",
        u"Fingerprint_714": "float",
        u"Fingerprint_776": "float",
        u"Fingerprint_779": "float",
        u"Fingerprint_791": "float",
        u"Fingerprint_797": "float",
        u"Fingerprint_798": "float",
        u"Fingerprint_800": "float",
        u"Fingerprint_812": "float",
        u"Fingerprint_818": "float",
        u"Fingerprint_820": "float",
        u"Fingerprint_821": "float",
        u"Fingerprint_822": "float",
        u"Fingerprint_826": "float",
        u"Fingerprint_830": "float",
        u"From_Sanger": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6

    H1_1 = tanh((-0.0167299676918421 + 0.0139402240388116 * indata[u"Fingerprint_576"] + 0.0124520369231252 * indata[u"Fingerprint_611"] + 0.000708259030772171 * indata[u"Fingerprint_617"] + 0.000972573167509275 * indata[u"Fingerprint_635"] + 0.00338920857351246 * indata[u"Fingerprint_643"] + -0.00429056731035652 * indata[u"Fingerprint_644"] + -0.00465940393388559 * indata[u"Fingerprint_647"] + 0.0299309790311872 * indata[u"Fingerprint_650"] + -0.0035565200263656 * indata[u"Fingerprint_658"] + -0.137611538575986 * indata[u"Fingerprint_659"] + -0.013872730858641 * indata[u"Fingerprint_667"] + -0.0227914810880229 * indata[u"Fingerprint_673"] + 0.000598629893975448 * indata[u"Fingerprint_685"] + -0.0353005794064076 * indata[u"Fingerprint_686"] + -0.000165129467525891 * indata[u"Fingerprint_696"] + 0.0119496411011436 * indata[u"Fingerprint_698"] + 0.00975506555754865 * indata[u"Fingerprint_702"] + 0.0364436121739159 * indata[u"Fingerprint_704"] + -0.000522307561044735 * indata[u"Fingerprint_707"] + -0.00282682225367308 * indata[u"Fingerprint_711"] + 0.00800006931604745 * indata[u"Fingerprint_712"] + -0.00573329218429963 * indata[u"Fingerprint_714"] + -0.000275023917042489 * indata[u"Fingerprint_776"] + 0.0451796491590293 * indata[u"Fingerprint_779"] + -0.0490387036914164 * indata[u"Fingerprint_791"] + -0.0276000900199787 * indata[u"Fingerprint_797"] + -0.0323844841539279 * indata[u"Fingerprint_798"] + -0.0001962862649915 * indata[u"Fingerprint_800"] + 0.0612115775375037 * indata[u"Fingerprint_812"] + 0.00622296034135147 * indata[u"Fingerprint_818"] + -0.00166889646123605 * indata[u"Fingerprint_820"] + -0.0108672447823194 * indata[u"Fingerprint_821"] + 0.0135653961773414 * indata[u"Fingerprint_822"] + 0.00615539300444979 * indata[u"Fingerprint_826"] + -0.00382263308298323 * indata[u"Fingerprint_830"] + 0.040962941124884 * indata[u"From_Sanger"]))

    H1_2 = tanh((-0.0296917160089214 + -0.000194275294605814 * indata[u"Fingerprint_576"] + 0.0394292271904627 * indata[u"Fingerprint_611"] + 0.0529658616302219 * indata[u"Fingerprint_617"] + -0.0382724712755121 * indata[u"Fingerprint_635"] + 0.00807791111448549 * indata[u"Fingerprint_643"] + 0.0100187456092004 * indata[u"Fingerprint_644"] + -0.00489175127588624 * indata[u"Fingerprint_647"] + 0.000900177725995761 * indata[u"Fingerprint_650"] + -0.0945560679679781 * indata[u"Fingerprint_658"] + -0.0103730014792417 * indata[u"Fingerprint_659"] + 0.00987388240269968 * indata[u"Fingerprint_667"] + 0.0353041334854244 * indata[u"Fingerprint_673"] + 0.0000462497515922649 * indata[u"Fingerprint_685"] + -0.0933631729561201 * indata[u"Fingerprint_686"] + 0.00221486585898439 * indata[u"Fingerprint_696"] + 0.0809982649313896 * indata[u"Fingerprint_698"] + 0.0206979686202445 * indata[u"Fingerprint_702"] + -0.024094605169386 * indata[u"Fingerprint_704"] + -0.0298018326807218 * indata[u"Fingerprint_707"] + -0.00459521778324638 * indata[u"Fingerprint_711"] + -0.108550745583117 * indata[u"Fingerprint_712"] + 0.0878640624059662 * indata[u"Fingerprint_714"] + 0.00708516672560532 * indata[u"Fingerprint_776"] + 0.0116058108391643 * indata[u"Fingerprint_779"] + 0.026717685384256 * indata[u"Fingerprint_791"] + -0.0597200571713683 * indata[u"Fingerprint_797"] + 0.000005440515333801 * indata[u"Fingerprint_798"] + 0.0488242542266631 * indata[u"Fingerprint_800"] + -0.000344885581833564 * indata[u"Fingerprint_812"] + 0.00170774270732102 * indata[u"Fingerprint_818"] + 0.000389601913218357 * indata[u"Fingerprint_820"] + 0.00255411213775033 * indata[u"Fingerprint_821"] + -0.00865938049675468 * indata[u"Fingerprint_822"] + -0.00331819720178581 * indata[u"Fingerprint_826"] + 0.0696076051277089 * indata[u"Fingerprint_830"] + -0.0155085589319374 * indata[u"From_Sanger"]))

    H1_3 = tanh((-0.0154091665899077 + -0.00096517080363628 * indata[u"Fingerprint_576"] + 0.000500416054552517 * indata[u"Fingerprint_611"] + 0.00314819320087412 * indata[u"Fingerprint_617"] + 0.000761917849934097 * indata[u"Fingerprint_635"] + 0.00248309828757512 * indata[u"Fingerprint_643"] + 0.00222923518828844 * indata[u"Fingerprint_644"] + 0.0000766836289082786 * indata[u"Fingerprint_647"] + -0.000333027749784521 * indata[u"Fingerprint_650"] + -0.00257073912644417 * indata[u"Fingerprint_658"] + -0.000666976133518117 * indata[u"Fingerprint_659"] + 0.000997033725143265 * indata[u"Fingerprint_667"] + 0.0692684563706012 * indata[u"Fingerprint_673"] + 0.000869394359126011 * indata[u"Fingerprint_685"] + -0.000176819285951365 * indata[u"Fingerprint_686"] + -0.00332601555686167 * indata[u"Fingerprint_696"] + 0.00883148326014792 * indata[u"Fingerprint_698"] + -0.00101179009253477 * indata[u"Fingerprint_702"] + -0.0000505751070062172 * indata[u"Fingerprint_704"] + -0.000922634122004641 * indata[u"Fingerprint_707"] + 0.000412772594334002 * indata[u"Fingerprint_711"] + -0.000106659327089389 * indata[u"Fingerprint_712"] + -0.00317972685608939 * indata[u"Fingerprint_714"] + -0.000163724251526033 * indata[u"Fingerprint_776"] + 0.0084087130101459 * indata[u"Fingerprint_779"] + -0.0342143398138613 * indata[u"Fingerprint_791"] + 0.000433800168684279 * indata[u"Fingerprint_797"] + 0.00234814774764166 * indata[u"Fingerprint_798"] + 0.00245321352193565 * indata[u"Fingerprint_800"] + -0.000379510822269735 * indata[u"Fingerprint_812"] + 0.0000415835892721472 * indata[u"Fingerprint_818"] + 0.000261301068029661 * indata[u"Fingerprint_820"] + 0.000501319633394489 * indata[u"Fingerprint_821"] + -0.00603894882076291 * indata[u"Fingerprint_822"] + -0.00216423547803126 * indata[u"Fingerprint_826"] + -0.000144582983223583 * indata[u"Fingerprint_830"] + -0.000503772006173197 * indata[u"From_Sanger"]))

    H1_4 = tanh((-0.0436386981017431 + 0.0574552808477885 * indata[u"Fingerprint_576"] + 0.00812963543904362 * indata[u"Fingerprint_611"] + -0.145195653423768 * indata[u"Fingerprint_617"] + -0.0190817711884732 * indata[u"Fingerprint_635"] + -0.0319238196799186 * indata[u"Fingerprint_643"] + -0.0153105763667033 * indata[u"Fingerprint_644"] + 0.000151191880833497 * indata[u"Fingerprint_647"] + -0.000804939330153913 * indata[u"Fingerprint_650"] + 0.0244624508797945 * indata[u"Fingerprint_658"] + -0.0116986191230462 * indata[u"Fingerprint_659"] + -0.0214339794925564 * indata[u"Fingerprint_667"] + -0.000204632643146997 * indata[u"Fingerprint_673"] + -0.0154474277074972 * indata[u"Fingerprint_685"] + -0.000153854432733221 * indata[u"Fingerprint_686"] + 0.0121600791634908 * indata[u"Fingerprint_696"] + -0.0000087922451908563 * indata[u"Fingerprint_698"] + 0.0317410359837335 * indata[u"Fingerprint_702"] + -0.00941810886555622 * indata[u"Fingerprint_704"] + -0.0218133979607425 * indata[u"Fingerprint_707"] + 0.00339019161659464 * indata[u"Fingerprint_711"] + 0.109178486325855 * indata[u"Fingerprint_712"] + -0.00304339444645735 * indata[u"Fingerprint_714"] + -0.00331654691208501 * indata[u"Fingerprint_776"] + 0.0286218395323635 * indata[u"Fingerprint_779"] + 0.00199079943215436 * indata[u"Fingerprint_791"] + 0.00641253200450175 * indata[u"Fingerprint_797"] + -0.00953214858588268 * indata[u"Fingerprint_798"] + 0.0136719795693929 * indata[u"Fingerprint_800"] + -0.00133714573713772 * indata[u"Fingerprint_812"] + 0.000274035105870297 * indata[u"Fingerprint_818"] + 0.0135408823425512 * indata[u"Fingerprint_820"] + 0.00549086841805803 * indata[u"Fingerprint_821"] + 0.011410656749598 * indata[u"Fingerprint_822"] + -0.0187446399547221 * indata[u"Fingerprint_826"] + -0.0738073109626211 * indata[u"Fingerprint_830"] + 0.0318101491979483 * indata[u"From_Sanger"]))

    H1_5 = tanh((0.0426522460401412 + -0.0416142921859934 * indata[u"Fingerprint_576"] + 0.00223115736412176 * indata[u"Fingerprint_611"] + -0.0000213073929161682 * indata[u"Fingerprint_617"] + -0.0342768968123049 * indata[u"Fingerprint_635"] + 0.00110460334600761 * indata[u"Fingerprint_643"] + 0.00647272459149519 * indata[u"Fingerprint_644"] + -0.00196728077908294 * indata[u"Fingerprint_647"] + -0.00903448726477837 * indata[u"Fingerprint_650"] + 0.00019289569056059 * indata[u"Fingerprint_658"] + -0.122800939243075 * indata[u"Fingerprint_659"] + 0.00523663654371872 * indata[u"Fingerprint_667"] + -0.00751696140901878 * indata[u"Fingerprint_673"] + 0.0421198972464894 * indata[u"Fingerprint_685"] + -0.0126075744595858 * indata[u"Fingerprint_686"] + 0.0418886697618775 * indata[u"Fingerprint_696"] + -0.0267495926778094 * indata[u"Fingerprint_698"] + -0.0310721143698545 * indata[u"Fingerprint_702"] + 0.0786350806153272 * indata[u"Fingerprint_704"] + 0.00173491220015554 * indata[u"Fingerprint_707"] + 0.00056983504004445 * indata[u"Fingerprint_711"] + -0.0114253458731362 * indata[u"Fingerprint_712"] + 0.00901857266608128 * indata[u"Fingerprint_714"] + 0.00318380918088222 * indata[u"Fingerprint_776"] + 0.00267515364876543 * indata[u"Fingerprint_779"] + 0.0135161145971705 * indata[u"Fingerprint_791"] + -0.000481245883793875 * indata[u"Fingerprint_797"] + 0.00128677650477869 * indata[u"Fingerprint_798"] + -0.0189952290012618 * indata[u"Fingerprint_800"] + 0.0534110335068293 * indata[u"Fingerprint_812"] + 0.00462432958466798 * indata[u"Fingerprint_818"] + -0.0195341388973345 * indata[u"Fingerprint_820"] + -0.0224302581391723 * indata[u"Fingerprint_821"] + -0.000176688693009744 * indata[u"Fingerprint_822"] + 0.00716419540964679 * indata[u"Fingerprint_826"] + 0.0370978665901149 * indata[u"Fingerprint_830"] + 0.0313604839784861 * indata[u"From_Sanger"]))

    H1_6 = tanh((-0.0617088352931633 + 0.0122814977782838 * indata[u"Fingerprint_576"] + 0.0243610317015223 * indata[u"Fingerprint_611"] + -0.141794498518869 * indata[u"Fingerprint_617"] + -0.0859561520802599 * indata[u"Fingerprint_635"] + -0.0376324673724882 * indata[u"Fingerprint_643"] + -0.000646746149562335 * indata[u"Fingerprint_644"] + 0.00102388730018591 * indata[u"Fingerprint_647"] + -0.0458210595151875 * indata[u"Fingerprint_650"] + -0.0298860465432092 * indata[u"Fingerprint_658"] + 0.0286788629842011 * indata[u"Fingerprint_659"] + 0.00194407244066747 * indata[u"Fingerprint_667"] + 0.00410446300865083 * indata[u"Fingerprint_673"] + 0.0208153903905041 * indata[u"Fingerprint_685"] + -0.0340050421540896 * indata[u"Fingerprint_686"] + 0.0595085307032957 * indata[u"Fingerprint_696"] + 0.0102212945517207 * indata[u"Fingerprint_698"] + 0.0107110773811973 * indata[u"Fingerprint_702"] + 0.00388254297691864 * indata[u"Fingerprint_704"] + -0.0439028521996218 * indata[u"Fingerprint_707"] + 0.00371205539519474 * indata[u"Fingerprint_711"] + 0.0359647935303358 * indata[u"Fingerprint_712"] + 0.0765564438933316 * indata[u"Fingerprint_714"] + 0.0044485392866756 * indata[u"Fingerprint_776"] + -0.0151851597540004 * indata[u"Fingerprint_779"] + 0.115680062305372 * indata[u"Fingerprint_791"] + -0.0000558355269934775 * indata[u"Fingerprint_797"] + 0.028034814384643 * indata[u"Fingerprint_798"] + 0.0311034638767149 * indata[u"Fingerprint_800"] + -0.0244325005833754 * indata[u"Fingerprint_812"] + -0.0016806750139658 * indata[u"Fingerprint_818"] + -0.000432430539138492 * indata[u"Fingerprint_820"] + -0.000081041092688405 * indata[u"Fingerprint_821"] + -0.00515703499631692 * indata[u"Fingerprint_822"] + -0.0255455458098244 * indata[u"Fingerprint_826"] + 0.000539430264247925 * indata[u"Fingerprint_830"] + 0.00866633294161501 * indata[u"From_Sanger"]))

    outdata[u"Predicted IC50_1"] = -134.238740050588 + -2904.37930226132 * H1_1 + 1648.57415515272 * H1_2 + -1392.04401132176 * H1_3 + 2862.49406725076 * H1_4 + 2314.45850762711 * H1_5 + -2350.00663058026 * H1_6

    return outdata[u"Predicted IC50_1"]


