from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """


def getInputMetadata():
    return {
        u"Fingerprint_576": "float",
        u"Fingerprint_588": "float",
        u"Fingerprint_611": "float",
        u"Fingerprint_617": "float",
        u"Fingerprint_629": "float",
        u"Fingerprint_635": "float",
        u"Fingerprint_643": "float",
        u"Fingerprint_644": "float",
        u"Fingerprint_650": "float",
        u"Fingerprint_667": "float",
        u"Fingerprint_677": "float",
        u"Fingerprint_685": "float",
        u"Fingerprint_686": "float",
        u"Fingerprint_696": "float",
        u"Fingerprint_698": "float",
        u"Fingerprint_702": "float",
        u"Fingerprint_704": "float",
        u"Fingerprint_707": "float",
        u"Fingerprint_711": "float",
        u"Fingerprint_714": "float",
        u"Fingerprint_791": "float",
        u"Fingerprint_797": "float",
        u"Fingerprint_798": "float",
        u"Fingerprint_800": "float",
        u"Fingerprint_813": "float",
        u"Fingerprint_818": "float",
        u"Fingerprint_820": "float",
        u"Fingerprint_821": "float",
        u"Fingerprint_822": "float",
        u"Fingerprint_824": "float",
        u"Fingerprint_826": "float",
        u"Fingerprint_830": "float",
        u"From_Sanger": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6

    H1_1 = tanh((-0.230254672178111 + 0.0661528455993021 * indata[u"Fingerprint_576"] + -0.0000477439293477543 * indata[u"Fingerprint_588"] + 0.0172724369582797 * indata[u"Fingerprint_611"] + -0.041236672922321 * indata[u"Fingerprint_617"] + -0.00292220186320789 * indata[u"Fingerprint_629"] + 0.00366449782894434 * indata[u"Fingerprint_635"] + -0.000971367553941359 * indata[u"Fingerprint_643"] + 0.0351356588529855 * indata[u"Fingerprint_644"] + -0.025634007326934 * indata[u"Fingerprint_650"] + 0.0915332269708562 * indata[u"Fingerprint_667"] + -0.0221498795379553 * indata[u"Fingerprint_677"] + -0.0362143629704369 * indata[u"Fingerprint_685"] + 0.0229717271994305 * indata[u"Fingerprint_686"] + 0.162636348493593 * indata[u"Fingerprint_696"] + -0.01492324806983 * indata[u"Fingerprint_698"] + -0.0111554841098914 * indata[u"Fingerprint_702"] + 0.00283369871527995 * indata[u"Fingerprint_704"] + -0.00097184303276314 * indata[u"Fingerprint_707"] + 0.0200552041544045 * indata[u"Fingerprint_711"] + -0.0137876584933169 * indata[u"Fingerprint_714"] + -0.00765369548445452 * indata[u"Fingerprint_791"] + -0.0439754864610898 * indata[u"Fingerprint_797"] + 0.00124629531582035 * indata[u"Fingerprint_798"] + 0.00681867748580816 * indata[u"Fingerprint_800"] + 0.203928136392167 * indata[u"Fingerprint_813"] + 0.153194210018142 * indata[u"Fingerprint_818"] + -0.030439457854268 * indata[u"Fingerprint_820"] + 0.0332135153960514 * indata[u"Fingerprint_821"] + 0.0961467298389983 * indata[u"Fingerprint_822"] + -0.0203079390534906 * indata[u"Fingerprint_824"] + -0.0204348218379772 * indata[u"Fingerprint_826"] + 0.0122845054421523 * indata[u"Fingerprint_830"] + 0.00317729824007246 * indata[u"From_Sanger"]))

    H1_2 = tanh((-0.0150738178592115 + -0.00204979239596444 * indata[u"Fingerprint_576"] + 0.0139893634313866 * indata[u"Fingerprint_588"] + -0.0285157093501855 * indata[u"Fingerprint_611"] + 0.0163304719453965 * indata[u"Fingerprint_617"] + -0.00228974524445321 * indata[u"Fingerprint_629"] + -0.0267748451308381 * indata[u"Fingerprint_635"] + -0.00889707501820045 * indata[u"Fingerprint_643"] + 0.0012341192748424 * indata[u"Fingerprint_644"] + 0.573995232364116 * indata[u"Fingerprint_650"] + 0.0626802267234156 * indata[u"Fingerprint_667"] + 0.00925526681842263 * indata[u"Fingerprint_677"] + 0.0702305461154016 * indata[u"Fingerprint_685"] + 0.0723052196339819 * indata[u"Fingerprint_686"] + 0.0477147205418617 * indata[u"Fingerprint_696"] + -0.0804630211851802 * indata[u"Fingerprint_698"] + 0.0172153992593816 * indata[u"Fingerprint_702"] + 0.0203609697802471 * indata[u"Fingerprint_704"] + -0.00108401414329376 * indata[u"Fingerprint_707"] + -0.0538097639450461 * indata[u"Fingerprint_711"] + 0.0121244027498374 * indata[u"Fingerprint_714"] + 0.0123499786492842 * indata[u"Fingerprint_791"] + 0.0395201504974004 * indata[u"Fingerprint_797"] + -0.0639673083612953 * indata[u"Fingerprint_798"] + -0.0246552874915914 * indata[u"Fingerprint_800"] + -0.0221687977116067 * indata[u"Fingerprint_813"] + 0.108114643138652 * indata[u"Fingerprint_818"] + 0.142724376765199 * indata[u"Fingerprint_820"] + -0.0409591273177531 * indata[u"Fingerprint_821"] + 0.00217544231462043 * indata[u"Fingerprint_822"] + -0.0869661089441705 * indata[u"Fingerprint_824"] + -0.0115843121140106 * indata[u"Fingerprint_826"] + -0.000637643400239057 * indata[u"Fingerprint_830"] + 0.0260031354007245 * indata[u"From_Sanger"]))

    H1_3 = tanh((0.233258922506309 + -0.201261248202665 * indata[u"Fingerprint_576"] + -0.0178115426080034 * indata[u"Fingerprint_588"] + 0.000945006886214678 * indata[u"Fingerprint_611"] + 0.0148689640756122 * indata[u"Fingerprint_617"] + -0.106739861378253 * indata[u"Fingerprint_629"] + -0.0271347854649527 * indata[u"Fingerprint_635"] + -0.0130443130793721 * indata[u"Fingerprint_643"] + 0.0000392093669476656 * indata[u"Fingerprint_644"] + -0.0678031082308225 * indata[u"Fingerprint_650"] + -0.0322715783756315 * indata[u"Fingerprint_667"] + -0.0292899493487941 * indata[u"Fingerprint_677"] + -0.0138266399189559 * indata[u"Fingerprint_685"] + 0.0516640522919087 * indata[u"Fingerprint_686"] + -0.0932204162733926 * indata[u"Fingerprint_696"] + -0.0442459026270098 * indata[u"Fingerprint_698"] + 0.0424513877935734 * indata[u"Fingerprint_702"] + 0.0311140236644156 * indata[u"Fingerprint_704"] + -0.0131639652417672 * indata[u"Fingerprint_707"] + -0.167717252618665 * indata[u"Fingerprint_711"] + -0.000166846052982005 * indata[u"Fingerprint_714"] + -0.093940629741169 * indata[u"Fingerprint_791"] + 0.070555926405083 * indata[u"Fingerprint_797"] + -0.0690356935274705 * indata[u"Fingerprint_798"] + -0.0478775421863542 * indata[u"Fingerprint_800"] + -0.0542547971313113 * indata[u"Fingerprint_813"] + -0.0641072363234973 * indata[u"Fingerprint_818"] + 0.0606335291334153 * indata[u"Fingerprint_820"] + 0.0316728982844983 * indata[u"Fingerprint_821"] + 0.00608024193530669 * indata[u"Fingerprint_822"] + 0.0201134819403951 * indata[u"Fingerprint_824"] + 0.0623749216932108 * indata[u"Fingerprint_826"] + 0.0220914007124214 * indata[u"Fingerprint_830"] + -0.00020812045311442 * indata[u"From_Sanger"]))

    H1_4 = tanh((-0.00766621350952593 + 0.00272801433303628 * indata[u"Fingerprint_576"] + -0.00155086816484183 * indata[u"Fingerprint_588"] + 0.0000851024405200213 * indata[u"Fingerprint_611"] + 0.0000653805276129835 * indata[u"Fingerprint_617"] + 0.0000523357106778024 * indata[u"Fingerprint_629"] + 0.000368229938410693 * indata[u"Fingerprint_635"] + -0.00121191566914725 * indata[u"Fingerprint_643"] + 0.0000550413834093077 * indata[u"Fingerprint_644"] + 0.000868301010731345 * indata[u"Fingerprint_650"] + 0.0000874972301578512 * indata[u"Fingerprint_667"] + 0.0063844382504147 * indata[u"Fingerprint_677"] + 0.000116357772649086 * indata[u"Fingerprint_685"] + 0.00149956718564832 * indata[u"Fingerprint_686"] + 0.000500699746042136 * indata[u"Fingerprint_696"] + -0.000324114603980383 * indata[u"Fingerprint_698"] + 0.000184415190321468 * indata[u"Fingerprint_702"] + 0.000174677040965152 * indata[u"Fingerprint_704"] + 0.000302233371760719 * indata[u"Fingerprint_707"] + 0.00707235528326791 * indata[u"Fingerprint_711"] + -0.00158943107706479 * indata[u"Fingerprint_714"] + -0.000552554831048174 * indata[u"Fingerprint_791"] + 0.000115883565180714 * indata[u"Fingerprint_797"] + 0.000851626349555355 * indata[u"Fingerprint_798"] + 0.000422739990577382 * indata[u"Fingerprint_800"] + 0.000247027846180552 * indata[u"Fingerprint_813"] + -0.000671810064438216 * indata[u"Fingerprint_818"] + -0.00215162973697208 * indata[u"Fingerprint_820"] + -0.000405135403939875 * indata[u"Fingerprint_821"] + 0.000767116573347162 * indata[u"Fingerprint_822"] + -0.000561299062389526 * indata[u"Fingerprint_824"] + 0.000563280723765469 * indata[u"Fingerprint_826"] + 0.000230188457480607 * indata[u"Fingerprint_830"] + 0.000180475011039656 * indata[u"From_Sanger"]))

    H1_5 = tanh((-0.269971732652798 + 0.000345472792374067 * indata[u"Fingerprint_576"] + 0.00259048151220091 * indata[u"Fingerprint_588"] + -0.0291138620599371 * indata[u"Fingerprint_611"] + 0.0650113575073816 * indata[u"Fingerprint_617"] + 0.165593247311381 * indata[u"Fingerprint_629"] + 0.000198002635826411 * indata[u"Fingerprint_635"] + -0.00640501672869532 * indata[u"Fingerprint_643"] + 0.150598931699313 * indata[u"Fingerprint_644"] + -0.0957055135995859 * indata[u"Fingerprint_650"] + 0.000551342785514962 * indata[u"Fingerprint_667"] + 0.0455389189898775 * indata[u"Fingerprint_677"] + 0.0713229136381016 * indata[u"Fingerprint_685"] + 0.0433645530563896 * indata[u"Fingerprint_686"] + 0.0125293037995245 * indata[u"Fingerprint_696"] + -0.00961050689599002 * indata[u"Fingerprint_698"] + -0.0262870932376 * indata[u"Fingerprint_702"] + -0.0177366585962477 * indata[u"Fingerprint_704"] + 0.020425607548371 * indata[u"Fingerprint_707"] + 0.0361185263901938 * indata[u"Fingerprint_711"] + 0.0441956576469615 * indata[u"Fingerprint_714"] + 0.0581315056514954 * indata[u"Fingerprint_791"] + -0.00662758026625675 * indata[u"Fingerprint_797"] + 0.0156067218595519 * indata[u"Fingerprint_798"] + -0.0377486800122427 * indata[u"Fingerprint_800"] + -0.0976547805796505 * indata[u"Fingerprint_813"] + 0.0684394474708127 * indata[u"Fingerprint_818"] + -0.000215985714673793 * indata[u"Fingerprint_820"] + 0.0027134859999251 * indata[u"Fingerprint_821"] + -0.0306845357160366 * indata[u"Fingerprint_822"] + 0.0155540277924951 * indata[u"Fingerprint_824"] + -0.000812097231663909 * indata[u"Fingerprint_826"] + -0.0132332221872224 * indata[u"Fingerprint_830"] + -0.0744006218801093 * indata[u"From_Sanger"]))

    H1_6 = tanh((0.0275446615971533 + -0.156429402892785 * indata[u"Fingerprint_576"] + -0.0289820381007682 * indata[u"Fingerprint_588"] + 0.0161458380259877 * indata[u"Fingerprint_611"] + 0.0227984012001914 * indata[u"Fingerprint_617"] + 0.0280082098265036 * indata[u"Fingerprint_629"] + -0.00263907803980457 * indata[u"Fingerprint_635"] + -0.0126307848400516 * indata[u"Fingerprint_643"] + 0.15299756944319 * indata[u"Fingerprint_644"] + -0.75826823787759 * indata[u"Fingerprint_650"] + -0.0167335857572283 * indata[u"Fingerprint_667"] + -0.0158988781532673 * indata[u"Fingerprint_677"] + -0.045043362373919 * indata[u"Fingerprint_685"] + 0.0455334378735311 * indata[u"Fingerprint_686"] + -0.00276953370080504 * indata[u"Fingerprint_696"] + 0.00526892461442685 * indata[u"Fingerprint_698"] + -0.00122290338296727 * indata[u"Fingerprint_702"] + 0.00126545541480252 * indata[u"Fingerprint_704"] + 0.00401928737718417 * indata[u"Fingerprint_707"] + -0.0794508378384833 * indata[u"Fingerprint_711"] + 0.0140778692774945 * indata[u"Fingerprint_714"] + -0.0646776644318373 * indata[u"Fingerprint_791"] + -0.000406264732681038 * indata[u"Fingerprint_797"] + -0.00171362069384526 * indata[u"Fingerprint_798"] + -0.0551732926493852 * indata[u"Fingerprint_800"] + 0.0459399810923734 * indata[u"Fingerprint_813"] + 0.0185137678930396 * indata[u"Fingerprint_818"] + -0.0836671685597648 * indata[u"Fingerprint_820"] + 0.098181630833862 * indata[u"Fingerprint_821"] + 0.0536119503130071 * indata[u"Fingerprint_822"] + 0.0928533166394956 * indata[u"Fingerprint_824"] + 0.0571607787621881 * indata[u"Fingerprint_826"] + 0.0236739812025508 * indata[u"Fingerprint_830"] + -0.0814885164224636 * indata[u"From_Sanger"]))

    outdata[u"Predicted IC50_1"] = 287.785399944934 + 1251.89457591732 * H1_1 + -1395.82402955605 * H1_2 + 1666.05583327892 * H1_3 + 204.022476324624 * H1_4 + 1361.80481974372 * H1_5 + -1596.30974567968 * H1_6

    return outdata[u"Predicted IC50_1"]


