library(glmnet)
mydata = read.table("./TrainingSet/AvgRank/haematopoietic.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0,family="gaussian",standardize=TRUE)
sink('./Model/EN/AvgRank/haematopoietic/haematopoietic_003.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
