library(glmnet)
mydata = read.table("./TrainingSet/LassoBIC/large_intestine.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=0.03,family="gaussian",standardize=FALSE)
sink('./Model/EN/Lasso/large_intestine/large_intestine_014.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
