library(glmnet)
mydata = read.table("./TrainingSet/RF/pleura.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0.03,family="gaussian",standardize=FALSE)
sink('./Model/EN/Classifier/pleura/pleura_016.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
