from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """

def getModelMetadata():
	return {"creator": u"Neural", "modelName": u"", "predicted": u"IC50", "table": u"endometrium", "version": u"14.1.0", "timestamp": u"2019-05-11T17:28:03Z"}


def getInputMetadata():
    return {
        u"CLS_average_ploidy": "float",
        u"EXP_NEK6_X_EXP_NUP37": "float",
        u"EXP_NEK6_X_EXP_TOP2A": "float",
        u"EXP_STK16_X_EXP_PEPD": "float",
        u"Fingerprint_611": "float",
        u"Fingerprint_617": "float",
        u"Fingerprint_629": "float",
        u"Fingerprint_635": "float",
        u"Fingerprint_644": "float",
        u"Fingerprint_646": "float",
        u"Fingerprint_672": "float",
        u"Fingerprint_677": "float",
        u"Fingerprint_685": "float",
        u"Fingerprint_697": "float",
        u"Fingerprint_698": "float",
        u"Fingerprint_710": "float",
        u"Fingerprint_712": "float",
        u"Fingerprint_776": "float",
        u"Fingerprint_797": "float",
        u"Fingerprint_813": "float",
        u"Fingerprint_819": "float",
        u"Fingerprint_822": "float",
        u"Fingerprint_824": "float",
        u"Fingerprint_834": "float",
        u"From_Sanger": "float",
        u"GO_0030878_EXP": "float",
        u"GO_0043114_X_GO_0045785": "float",
        u"PKA_105_CSV_X_Fingerprint_826": "float",
        u"PKA_162_CSV_X_Fingerprint_644": "float",
        u"PKA_197_ENG_X_Fingerprint_818": "float",
        u"PKA_217_ASA_X_Fingerprint_826": "float",
        u"REC_R_HSA_141409": "float",
        u"REC_R_HSA_141409_EXP": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H2_1
    # H2_2
    # H2_3
    # H2_4
    # H2_5
    # H2_6
    # H2_7
    # H2_8
    # H2_9
    # H2_10
    # H2_11
    # H1_1
    # H1_2
    # H1_3
    # H1_4

    H2_1 = tanh((-16.6664074627892 + -0.0651898740615462 * indata[u"CLS_average_ploidy"] + 0.0601865296481369 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.0721721733280957 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + 0.0816166237162779 * indata[u"EXP_STK16_X_EXP_PEPD"] + -1.04088923617008 * indata[u"Fingerprint_611"] + -5.87730671268039 * indata[u"Fingerprint_617"] + 3.96303548066997 * indata[u"Fingerprint_629"] + -2.45096311480857 * indata[u"Fingerprint_635"] + -5.2052419953386 * indata[u"Fingerprint_644"] + -2.3212726875264 * indata[u"Fingerprint_646"] + -5.99507961651609 * indata[u"Fingerprint_672"] + 5.18408436903017 * indata[u"Fingerprint_677"] + 0.184097818927395 * indata[u"Fingerprint_685"] + -4.321775542352 * indata[u"Fingerprint_697"] + -1.59420610471792 * indata[u"Fingerprint_698"] + 5.42984536226339 * indata[u"Fingerprint_710"] + -0.391881830809823 * indata[u"Fingerprint_712"] + 0.0949925431677596 * indata[u"Fingerprint_776"] + -3.03317533942518 * indata[u"Fingerprint_797"] + 8.24414948910966 * indata[u"Fingerprint_813"] + 5.80489266595107 * indata[u"Fingerprint_819"] + 1.90254326408651 * indata[u"Fingerprint_822"] + 0.0831811251187724 * indata[u"Fingerprint_824"] + 3.63198540814362 * indata[u"Fingerprint_834"] + 11.4237178343262 * indata[u"From_Sanger"] + 0.201497335967951 * indata[u"GO_0030878_EXP"] + 0.827861899487015 * indata[u"GO_0043114_X_GO_0045785"] + 7.86890079960057 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + -0.536089803154947 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + 0.696064723063163 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + -0.0288879251416774 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + -0.71604218988719 * indata[u"REC_R_HSA_141409"] + 0.0181109581454876 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_2 = tanh((12.1667554547481 + 0.843291152086916 * indata[u"CLS_average_ploidy"] + -0.118274201355228 * indata[u"EXP_NEK6_X_EXP_NUP37"] + -0.0124388143941573 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.0343517786913326 * indata[u"EXP_STK16_X_EXP_PEPD"] + 3.43334354690877 * indata[u"Fingerprint_611"] + 0.0606014480200259 * indata[u"Fingerprint_617"] + 0.87139457531931 * indata[u"Fingerprint_629"] + 3.41554022919296 * indata[u"Fingerprint_635"] + -1.31553354193769 * indata[u"Fingerprint_644"] + -4.52505949967595 * indata[u"Fingerprint_646"] + -0.952125029770893 * indata[u"Fingerprint_672"] + 4.32218345409544 * indata[u"Fingerprint_677"] + 2.47861734896797 * indata[u"Fingerprint_685"] + 2.25909629152402 * indata[u"Fingerprint_697"] + -5.02542964818994 * indata[u"Fingerprint_698"] + -9.44146230207596 * indata[u"Fingerprint_710"] + -3.81326696899498 * indata[u"Fingerprint_712"] + 2.21779207833809 * indata[u"Fingerprint_776"] + 3.30800557451764 * indata[u"Fingerprint_797"] + -9.45808898889415 * indata[u"Fingerprint_813"] + 2.6262946454115 * indata[u"Fingerprint_819"] + -8.45815886234081 * indata[u"Fingerprint_822"] + 5.30064771437111 * indata[u"Fingerprint_824"] + -1.30868128144493 * indata[u"Fingerprint_834"] + -2.94739702642411 * indata[u"From_Sanger"] + 0.0587447474126618 * indata[u"GO_0030878_EXP"] + -1.53248425617263 * indata[u"GO_0043114_X_GO_0045785"] + -4.38190533433576 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + 1.76137096261312 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + 0.204570257786977 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.0533840661052181 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + 0.0124948801479981 * indata[u"REC_R_HSA_141409"] + 0.0355408065151145 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_3 = tanh((2.23184979247663 + 0.957494882728831 * indata[u"CLS_average_ploidy"] + -0.0477167048745544 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.00283030433601378 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + 0.0356740821310383 * indata[u"EXP_STK16_X_EXP_PEPD"] + -0.896655913708283 * indata[u"Fingerprint_611"] + -0.0713146772903466 * indata[u"Fingerprint_617"] + -1.56142101755244 * indata[u"Fingerprint_629"] + 6.64087455458283 * indata[u"Fingerprint_635"] + -3.013633681967 * indata[u"Fingerprint_644"] + -3.75786232154341 * indata[u"Fingerprint_646"] + 2.1334885511648 * indata[u"Fingerprint_672"] + -1.57287742512458 * indata[u"Fingerprint_677"] + 2.10496032863008 * indata[u"Fingerprint_685"] + 2.72536125532913 * indata[u"Fingerprint_697"] + -8.85774528832439 * indata[u"Fingerprint_698"] + 2.91490817863078 * indata[u"Fingerprint_710"] + -2.09588598295144 * indata[u"Fingerprint_712"] + -1.94484262532546 * indata[u"Fingerprint_776"] + -6.8356009631516 * indata[u"Fingerprint_797"] + -11.1643469699055 * indata[u"Fingerprint_813"] + 0.43428319242722 * indata[u"Fingerprint_819"] + 0.279956314095118 * indata[u"Fingerprint_822"] + 0.663386423362605 * indata[u"Fingerprint_824"] + -8.44628992357209 * indata[u"Fingerprint_834"] + 3.36300673964171 * indata[u"From_Sanger"] + -0.0359975464029447 * indata[u"GO_0030878_EXP"] + 0.864493652817088 * indata[u"GO_0043114_X_GO_0045785"] + 2.08649749664573 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + -0.778207174762473 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + -0.0588402173979503 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + -0.02285887329498 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + 0.531110356762859 * indata[u"REC_R_HSA_141409"] + -0.148902232874298 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_4 = tanh((-3.15631075582822 + 0.627559774252484 * indata[u"CLS_average_ploidy"] + 0.144643008950344 * indata[u"EXP_NEK6_X_EXP_NUP37"] + -0.0846880069963453 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.077356012036494 * indata[u"EXP_STK16_X_EXP_PEPD"] + -2.88349528436044 * indata[u"Fingerprint_611"] + 4.04173513588838 * indata[u"Fingerprint_617"] + -2.79325597036496 * indata[u"Fingerprint_629"] + 4.14577211195033 * indata[u"Fingerprint_635"] + -3.16137178148344 * indata[u"Fingerprint_644"] + 5.76288732220773 * indata[u"Fingerprint_646"] + -1.28181071202818 * indata[u"Fingerprint_672"] + 6.38048547281453 * indata[u"Fingerprint_677"] + -2.49681366105544 * indata[u"Fingerprint_685"] + 1.92898221389266 * indata[u"Fingerprint_697"] + 1.17882457995765 * indata[u"Fingerprint_698"] + -2.36613678362394 * indata[u"Fingerprint_710"] + 0.0326261570374228 * indata[u"Fingerprint_712"] + -0.133689884320075 * indata[u"Fingerprint_776"] + -7.719314197339 * indata[u"Fingerprint_797"] + -1.55277858177697 * indata[u"Fingerprint_813"] + -1.37567547389195 * indata[u"Fingerprint_819"] + -6.60189938793824 * indata[u"Fingerprint_822"] + 8.31136539684439 * indata[u"Fingerprint_824"] + 1.66949047893254 * indata[u"Fingerprint_834"] + -4.10736855579799 * indata[u"From_Sanger"] + -0.142568038744436 * indata[u"GO_0030878_EXP"] + 0.821855155303342 * indata[u"GO_0043114_X_GO_0045785"] + 2.37831684107329 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + 0.1171843772076 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + 0.732631517468623 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + -0.15949000161604 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + 1.41560311796399 * indata[u"REC_R_HSA_141409"] + -0.198564100462346 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_5 = tanh((1.10904960907743 + 0.418943599321878 * indata[u"CLS_average_ploidy"] + 0.0228863602890135 * indata[u"EXP_NEK6_X_EXP_NUP37"] + -0.018415075130311 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + 0.0242160014669789 * indata[u"EXP_STK16_X_EXP_PEPD"] + -2.51976273335683 * indata[u"Fingerprint_611"] + -6.68128050177282 * indata[u"Fingerprint_617"] + 3.53231416722224 * indata[u"Fingerprint_629"] + 3.89177320439868 * indata[u"Fingerprint_635"] + -3.21564684888361 * indata[u"Fingerprint_644"] + -5.30139879748372 * indata[u"Fingerprint_646"] + 4.0937302558972 * indata[u"Fingerprint_672"] + -6.60269436094827 * indata[u"Fingerprint_677"] + 0.936557322813259 * indata[u"Fingerprint_685"] + 3.20746732058901 * indata[u"Fingerprint_697"] + 1.41623623584624 * indata[u"Fingerprint_698"] + 1.64886604690461 * indata[u"Fingerprint_710"] + -0.944427109683353 * indata[u"Fingerprint_712"] + 2.29896578823434 * indata[u"Fingerprint_776"] + -0.194016679111791 * indata[u"Fingerprint_797"] + -8.70631021054703 * indata[u"Fingerprint_813"] + 1.82342515970581 * indata[u"Fingerprint_819"] + 4.9368725408896 * indata[u"Fingerprint_822"] + 3.28108764000902 * indata[u"Fingerprint_824"] + 0.488979040795736 * indata[u"Fingerprint_834"] + -1.91336459926497 * indata[u"From_Sanger"] + 0.113815771433523 * indata[u"GO_0030878_EXP"] + -0.747959450356947 * indata[u"GO_0043114_X_GO_0045785"] + 12.1951046858391 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + -0.47261754574793 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + 1.11155290185004 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + -0.175471941761897 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + -0.161981787075541 * indata[u"REC_R_HSA_141409"] + -0.05511165748051 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_6 = tanh((-11.3018839361003 + 0.524064425540577 * indata[u"CLS_average_ploidy"] + 0.0816600373817399 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.0756043304475558 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.053352016534751 * indata[u"EXP_STK16_X_EXP_PEPD"] + -0.168042676629212 * indata[u"Fingerprint_611"] + 1.1317127963882 * indata[u"Fingerprint_617"] + 6.21724419871143 * indata[u"Fingerprint_629"] + 4.04631936511706 * indata[u"Fingerprint_635"] + -4.48591310041889 * indata[u"Fingerprint_644"] + 0.487210497041432 * indata[u"Fingerprint_646"] + -0.755916891974293 * indata[u"Fingerprint_672"] + 6.67160998656002 * indata[u"Fingerprint_677"] + 0.00912999507729886 * indata[u"Fingerprint_685"] + -6.24115815534479 * indata[u"Fingerprint_697"] + -3.72037822888828 * indata[u"Fingerprint_698"] + 1.45789187346937 * indata[u"Fingerprint_710"] + -3.35688272441777 * indata[u"Fingerprint_712"] + 4.83206483452951 * indata[u"Fingerprint_776"] + 2.85768208195336 * indata[u"Fingerprint_797"] + -0.888690602783749 * indata[u"Fingerprint_813"] + -2.67340526690241 * indata[u"Fingerprint_819"] + 9.40492215418117 * indata[u"Fingerprint_822"] + -1.9283920506481 * indata[u"Fingerprint_824"] + 4.29650673633407 * indata[u"Fingerprint_834"] + -2.8901600434796 * indata[u"From_Sanger"] + 0.225861896717903 * indata[u"GO_0030878_EXP"] + 3.54650597521738 * indata[u"GO_0043114_X_GO_0045785"] + 5.49252610034685 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + 3.55437713251444 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + -2.19265047684735 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.3209235041538 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + -0.950249482566909 * indata[u"REC_R_HSA_141409"] + -0.0338176114199573 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_7 = tanh((8.67048598168795 + -1.17517345550069 * indata[u"CLS_average_ploidy"] + 0.118475736317865 * indata[u"EXP_NEK6_X_EXP_NUP37"] + -0.0194642168347391 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.0105609600466293 * indata[u"EXP_STK16_X_EXP_PEPD"] + -2.5376970307394 * indata[u"Fingerprint_611"] + -0.985575308446853 * indata[u"Fingerprint_617"] + -4.23040366674614 * indata[u"Fingerprint_629"] + -0.660689391607537 * indata[u"Fingerprint_635"] + -4.53989019505769 * indata[u"Fingerprint_644"] + -4.29027183457005 * indata[u"Fingerprint_646"] + 0.433324116851694 * indata[u"Fingerprint_672"] + -9.0863448707653 * indata[u"Fingerprint_677"] + -0.0159807962127315 * indata[u"Fingerprint_685"] + -2.76768322764747 * indata[u"Fingerprint_697"] + -3.62162639001152 * indata[u"Fingerprint_698"] + 6.51418369064536 * indata[u"Fingerprint_710"] + -3.2943681320721 * indata[u"Fingerprint_712"] + -2.91048577339392 * indata[u"Fingerprint_776"] + -3.17135457129421 * indata[u"Fingerprint_797"] + 0.20063775576755 * indata[u"Fingerprint_813"] + -7.99868386072663 * indata[u"Fingerprint_819"] + -5.57578060010681 * indata[u"Fingerprint_822"] + 3.97448472006411 * indata[u"Fingerprint_824"] + -5.7740782429326 * indata[u"Fingerprint_834"] + 1.87576007230024 * indata[u"From_Sanger"] + 0.00330773832448604 * indata[u"GO_0030878_EXP"] + 0.411441332485109 * indata[u"GO_0043114_X_GO_0045785"] + -6.4444474604693 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + 3.17142884777246 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + -0.502970716348267 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + -0.111421735362261 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + -0.640040628733317 * indata[u"REC_R_HSA_141409"] + -0.128187675763377 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_8 = tanh((2.08277920988089 + -1.70620507707286 * indata[u"CLS_average_ploidy"] + 0.118110346658565 * indata[u"EXP_NEK6_X_EXP_NUP37"] + -0.000378193090768161 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.0319373271933988 * indata[u"EXP_STK16_X_EXP_PEPD"] + -3.17570994429183 * indata[u"Fingerprint_611"] + -1.99790866036175 * indata[u"Fingerprint_617"] + 6.36810552900099 * indata[u"Fingerprint_629"] + 3.18329553375905 * indata[u"Fingerprint_635"] + -3.34541070948076 * indata[u"Fingerprint_644"] + -0.791818024840044 * indata[u"Fingerprint_646"] + -0.0762303634579531 * indata[u"Fingerprint_672"] + -3.43941088099225 * indata[u"Fingerprint_677"] + -0.345119056032493 * indata[u"Fingerprint_685"] + -2.86917218845321 * indata[u"Fingerprint_697"] + -2.03321365373509 * indata[u"Fingerprint_698"] + 3.27186324951108 * indata[u"Fingerprint_710"] + 3.12302523180375 * indata[u"Fingerprint_712"] + 2.71664400269178 * indata[u"Fingerprint_776"] + 0.432127446758263 * indata[u"Fingerprint_797"] + -0.516782888206382 * indata[u"Fingerprint_813"] + -7.87308916780082 * indata[u"Fingerprint_819"] + -5.78521880089171 * indata[u"Fingerprint_822"] + 1.97691360551747 * indata[u"Fingerprint_824"] + 2.40230368961863 * indata[u"Fingerprint_834"] + 0.260606539773429 * indata[u"From_Sanger"] + 0.0998391885586015 * indata[u"GO_0030878_EXP"] + -0.435855448206605 * indata[u"GO_0043114_X_GO_0045785"] + 2.89831536353287 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + 8.54805784658297 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + 0.295575405282893 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.0624578274112759 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + -0.132274126206425 * indata[u"REC_R_HSA_141409"] + 0.0260999182948561 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_9 = tanh((-13.7147495574066 + -1.19196857348515 * indata[u"CLS_average_ploidy"] + 0.180127042374469 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.171901430410865 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.104304951675559 * indata[u"EXP_STK16_X_EXP_PEPD"] + -0.990127801516806 * indata[u"Fingerprint_611"] + -5.26304320454165 * indata[u"Fingerprint_617"] + 1.6875359066852 * indata[u"Fingerprint_629"] + 2.74524313417315 * indata[u"Fingerprint_635"] + -0.330924262951471 * indata[u"Fingerprint_644"] + 1.8290027086047 * indata[u"Fingerprint_646"] + -1.16955742970665 * indata[u"Fingerprint_672"] + 9.98254325966486 * indata[u"Fingerprint_677"] + 0.35825444502402 * indata[u"Fingerprint_685"] + -3.73024217774004 * indata[u"Fingerprint_697"] + -0.468192831174922 * indata[u"Fingerprint_698"] + -4.31486229177247 * indata[u"Fingerprint_710"] + -2.60796768338056 * indata[u"Fingerprint_712"] + 1.76035811574955 * indata[u"Fingerprint_776"] + 1.59946424604644 * indata[u"Fingerprint_797"] + -5.38217196887163 * indata[u"Fingerprint_813"] + 3.4065353464359 * indata[u"Fingerprint_819"] + -3.68515556673279 * indata[u"Fingerprint_822"] + 8.70608235569673 * indata[u"Fingerprint_824"] + 4.68689347386216 * indata[u"Fingerprint_834"] + -1.39857376655183 * indata[u"From_Sanger"] + 0.108017023432096 * indata[u"GO_0030878_EXP"] + -0.849237047768491 * indata[u"GO_0043114_X_GO_0045785"] + 9.12212300447327 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + 0.837128782024182 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + -1.46289738477417 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + -0.265052832711087 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + -0.401537351187535 * indata[u"REC_R_HSA_141409"] + -0.107404202817314 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_10 = tanh((5.21812629838001 + 1.52915226553826 * indata[u"CLS_average_ploidy"] + 0.0847052201970126 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.0196368101804048 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.116733617414138 * indata[u"EXP_STK16_X_EXP_PEPD"] + 1.81916439286049 * indata[u"Fingerprint_611"] + 4.21142376889518 * indata[u"Fingerprint_617"] + -2.04444564885177 * indata[u"Fingerprint_629"] + -9.45286194541347 * indata[u"Fingerprint_635"] + 0.406811045695829 * indata[u"Fingerprint_644"] + -3.9695192409193 * indata[u"Fingerprint_646"] + -9.14121842305547 * indata[u"Fingerprint_672"] + -4.49668922605891 * indata[u"Fingerprint_677"] + 0.169784118271378 * indata[u"Fingerprint_685"] + -1.88108179450126 * indata[u"Fingerprint_697"] + -1.96312464101572 * indata[u"Fingerprint_698"] + 2.50004349503889 * indata[u"Fingerprint_710"] + -4.85531749206683 * indata[u"Fingerprint_712"] + 3.49795574755892 * indata[u"Fingerprint_776"] + -0.252122331988971 * indata[u"Fingerprint_797"] + 6.48298697492603 * indata[u"Fingerprint_813"] + 4.20936157833767 * indata[u"Fingerprint_819"] + -7.01207836195081 * indata[u"Fingerprint_822"] + -0.435822807720463 * indata[u"Fingerprint_824"] + 3.01411611059275 * indata[u"Fingerprint_834"] + -2.65348732955937 * indata[u"From_Sanger"] + 0.107080430311499 * indata[u"GO_0030878_EXP"] + -1.11699146281429 * indata[u"GO_0043114_X_GO_0045785"] + 12.7127156308622 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + -0.408476914273417 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + 1.07417789500114 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.082080228208167 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + -0.475385759089145 * indata[u"REC_R_HSA_141409"] + 0.0820885960526529 * indata[u"REC_R_HSA_141409_EXP"]))

    H2_11 = tanh((-9.9486067465806 + -0.586145617723473 * indata[u"CLS_average_ploidy"] + -0.088695648056323 * indata[u"EXP_NEK6_X_EXP_NUP37"] + -0.0219325922284475 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + 0.0575778109121231 * indata[u"EXP_STK16_X_EXP_PEPD"] + -1.15384573106871 * indata[u"Fingerprint_611"] + -4.32132994848747 * indata[u"Fingerprint_617"] + 3.16158187552971 * indata[u"Fingerprint_629"] + 2.93110734887992 * indata[u"Fingerprint_635"] + 2.00989309758801 * indata[u"Fingerprint_644"] + 5.08694733150862 * indata[u"Fingerprint_646"] + 1.43435948507006 * indata[u"Fingerprint_672"] + 3.26096033263185 * indata[u"Fingerprint_677"] + 2.65167199086687 * indata[u"Fingerprint_685"] + -0.731858304501885 * indata[u"Fingerprint_697"] + 1.00814840681225 * indata[u"Fingerprint_698"] + 4.57242745850611 * indata[u"Fingerprint_710"] + -0.28215673597282 * indata[u"Fingerprint_712"] + 2.44998856803452 * indata[u"Fingerprint_776"] + 0.215263777413412 * indata[u"Fingerprint_797"] + 8.80733721596888 * indata[u"Fingerprint_813"] + 5.18203677077387 * indata[u"Fingerprint_819"] + 6.044658280824 * indata[u"Fingerprint_822"] + 1.68991907805316 * indata[u"Fingerprint_824"] + 8.45033745344599 * indata[u"Fingerprint_834"] + 1.37017535680755 * indata[u"From_Sanger"] + 0.214056668019652 * indata[u"GO_0030878_EXP"] + -0.917915136397663 * indata[u"GO_0043114_X_GO_0045785"] + 4.33894279068641 * indata[u"PKA_105_CSV_X_Fingerprint_826"] + 1.0016461948274 * indata[u"PKA_162_CSV_X_Fingerprint_644"] + -2.15021018685956 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.128119409011295 * indata[u"PKA_217_ASA_X_Fingerprint_826"] + 0.309708591685081 * indata[u"REC_R_HSA_141409"] + 0.0417669634633131 * indata[u"REC_R_HSA_141409_EXP"]))

    H1_1 = tanh((-0.587621527643059 + 1.84519738381741 * H2_1 + -0.206467362559346 * H2_10 + -2.44733041601351 * H2_11 + -0.15787514384643 * H2_2 + 2.31869189164644 * H2_3 + -2.35346861835203 * H2_4 + 0.135202597413958 * H2_5 + -0.516445581324038 * H2_6 + 3.90738404871873 * H2_7 + 0.7361033358846 * H2_8 + 0.173965445407302 * H2_9))

    H1_2 = tanh((2.57825399022892 + -2.39722966667776 * H2_1 + 0.419482100165058 * H2_10 + 0.821084778207268 * H2_11 + -0.0523867820645686 * H2_2 + 1.98070524921512 * H2_3 + -0.651839737930158 * H2_4 + 0.464757040288784 * H2_5 + -0.85754800732663 * H2_6 + -0.023504229896275 * H2_7 + -1.45790713092346 * H2_8 + -1.26213315003713 * H2_9))

    H1_3 = tanh((0.0337432033374297 + -0.87084277000553 * H2_1 + 0.676684270338268 * H2_10 + 0.756903478332234 * H2_11 + -1.39832668856378 * H2_2 + 0.642009845517179 * H2_3 + 2.71575894972545 * H2_4 + 1.14878942191072 * H2_5 + -0.483346560684558 * H2_6 + -3.33131162138997 * H2_7 + 1.20204703267962 * H2_8 + 0.0227118417634556 * H2_9))

    H1_4 = tanh((3.09151965650491 + -0.664531021982698 * H2_1 + 2.49038904562362 * H2_10 + 1.31020965298349 * H2_11 + -0.448351652365362 * H2_2 + 0.177783284755267 * H2_3 + -0.26008863763674 * H2_4 + 2.05803351007456 * H2_5 + -0.974275900824932 * H2_6 + 0.401359053190726 * H2_7 + -1.06045356787106 * H2_8 + 1.93157360573799 * H2_9))

    outdata[u"Predicted IC50_1"] = 0.769076326253548 + 1.91284332271338 * H1_1 + 1.88165801904557 * H1_2 + 2.05673774789845 * H1_3 + 1.75060022843596 * H1_4

    return outdata[u"Predicted IC50_1"]


