library(glmnet)
mydata = read.table("./TrainingSet/RF/central_nervous_system.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=0.55,family="gaussian",standardize=FALSE)
sink('./Model/EN/Classifier/central_nervous_system/central_nervous_system_062.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
