library(glmnet)
mydata = read.table('/Data/Training/NoX/haematopoietic.csv',head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
lasso = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=1,family="gaussian")
sink('/Data/Model/NoX_Lasso/haematopoietic.txt',append=TRUE)
print(lasso)
sink()
