library(glmnet)
mydata = read.table("./TrainingSet/AvgRank/upper_aerodigestive_tract.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=0.45,family="gaussian",standardize=FALSE)
sink('./Model/EN/AvgRank/upper_aerodigestive_tract/upper_aerodigestive_tract_054.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
