from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """

def getModelMetadata():
	return {"creator": u"Neural", "modelName": u"", "predicted": u"IC50", "table": u"ovary", "version": u"14.1.0", "timestamp": u"2019-07-31T18:26:31Z"}


def getInputMetadata():
    return {
        u"EXP_ACVR2B": "float",
        u"EXP_SBK1": "float",
        u"EXP_SBK2": "float",
        u"EXP_STK10": "float",
        u"EXP_STK19": "float",
        u"GO_0060612": "float",
        u"GO_0061024": "float",
        u"MUT_GUCY2C": "float",
        u"MUT_RPS6KB2": "float",
        u"MUT_RPS6KB2_EXP": "float",
        u"MUT_TRPM6_EXP": "float",
        u"PKA_260_ENG": "float",
        u"PKA_260_EXP": "float",
        u"PWY_R_HSA_1643685_CSV": "float",
        u"PWY_R_HSA_170834_EXP": "float",
        u"REC_R_HSA_198640": "float",
        u"SDOM_subdomainIV": "float",
        u"SFAM_DYRK1_EXP": "float",
        u"SFAM_FJ": "float",
        u"SFAM_FJ_EXP": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6
    # H1_7
    # H1_8
    # H1_9
    # H1_10
    # H1_11

    H1_1 = tanh((6.42106150504976 + 0.0576641030062349 * indata[u"EXP_ACVR2B"] + -0.721396689964344 * indata[u"EXP_SBK1"] + -1.75200890248026 * indata[u"EXP_SBK2"] + -0.629654243318902 * indata[u"EXP_STK10"] + 1.06699873859135 * indata[u"EXP_STK19"] + 3.37123536477539 * indata[u"GO_0060612"] + -0.0625156839296206 * indata[u"GO_0061024"] + -1.76616320982921 * indata[u"MUT_GUCY2C"] + 0.0126123992521765 * indata[u"MUT_RPS6KB2"] + 0.520071263556123 * indata[u"MUT_RPS6KB2_EXP"] + -0.720005670908084 * indata[u"MUT_TRPM6_EXP"] + -0.795721198960791 * indata[u"PKA_260_ENG"] + 0.109038805637531 * indata[u"PKA_260_EXP"] + 1.54119453543105 * indata[u"PWY_R_HSA_1643685_CSV"] + 0.783160826728152 * indata[u"PWY_R_HSA_170834_EXP"] + 1.75735205876326 * indata[u"REC_R_HSA_198640"] + 0.663085002116318 * indata[u"SDOM_subdomainIV"] + 0.386241318880563 * indata[u"SFAM_DYRK1_EXP"] + -0.417480388992305 * indata[u"SFAM_FJ"] + 0.596172929801846 * indata[u"SFAM_FJ_EXP"]))

    H1_2 = tanh((-22.5769880987254 + 0.00235799402116473 * indata[u"EXP_ACVR2B"] + -0.34505185176276 * indata[u"EXP_SBK1"] + 3.97042087974197 * indata[u"EXP_SBK2"] + 2.03562671917048 * indata[u"EXP_STK10"] + 0.552136355575545 * indata[u"EXP_STK19"] + 0.0515516869779436 * indata[u"GO_0060612"] + 1.45111013466227 * indata[u"GO_0061024"] + 1.81383184493844 * indata[u"MUT_GUCY2C"] + -1.63048120183836 * indata[u"MUT_RPS6KB2"] + 0.364520129131277 * indata[u"MUT_RPS6KB2_EXP"] + -0.143695791828411 * indata[u"MUT_TRPM6_EXP"] + -0.256356959421052 * indata[u"PKA_260_ENG"] + 0.514234365222908 * indata[u"PKA_260_EXP"] + 0.658939677326784 * indata[u"PWY_R_HSA_1643685_CSV"] + -0.0529203570816418 * indata[u"PWY_R_HSA_170834_EXP"] + -0.92089076918291 * indata[u"REC_R_HSA_198640"] + 1.2357359544035 * indata[u"SDOM_subdomainIV"] + 0.280161704556995 * indata[u"SFAM_DYRK1_EXP"] + 0.613636528705445 * indata[u"SFAM_FJ"] + -0.0764067961154233 * indata[u"SFAM_FJ_EXP"]))

    H1_3 = tanh((-0.78072776968907 + 0.615805078287149 * indata[u"EXP_ACVR2B"] + 0.13546861183415 * indata[u"EXP_SBK1"] + -3.66677940977722 * indata[u"EXP_SBK2"] + -0.65215119253179 * indata[u"EXP_STK10"] + 4.08438170195981 * indata[u"EXP_STK19"] + -0.459142665479569 * indata[u"GO_0060612"] + -1.43030850292888 * indata[u"GO_0061024"] + -0.526321313558693 * indata[u"MUT_GUCY2C"] + -0.260362395692993 * indata[u"MUT_RPS6KB2"] + 0.996633259684157 * indata[u"MUT_RPS6KB2_EXP"] + 0.300198394356484 * indata[u"MUT_TRPM6_EXP"] + 0.010948865071354 * indata[u"PKA_260_ENG"] + -0.0846764067631656 * indata[u"PKA_260_EXP"] + 1.89249792137331 * indata[u"PWY_R_HSA_1643685_CSV"] + 0.592018903077753 * indata[u"PWY_R_HSA_170834_EXP"] + -1.51565689007976 * indata[u"REC_R_HSA_198640"] + -0.386638221600121 * indata[u"SDOM_subdomainIV"] + -0.692040778288473 * indata[u"SFAM_DYRK1_EXP"] + 1.02143041521627 * indata[u"SFAM_FJ"] + -0.634090885741921 * indata[u"SFAM_FJ_EXP"]))

    H1_4 = tanh((17.3803208661169 + 0.116678201773415 * indata[u"EXP_ACVR2B"] + -0.123248935352892 * indata[u"EXP_SBK1"] + -2.66657624095448 * indata[u"EXP_SBK2"] + -0.277915651864667 * indata[u"EXP_STK10"] + -2.28933611690476 * indata[u"EXP_STK19"] + 0.116058518281804 * indata[u"GO_0060612"] + -0.776627832662232 * indata[u"GO_0061024"] + 1.3827322454012 * indata[u"MUT_GUCY2C"] + 0.318490405072471 * indata[u"MUT_RPS6KB2"] + 0.340273356821251 * indata[u"MUT_RPS6KB2_EXP"] + -0.683329210422497 * indata[u"MUT_TRPM6_EXP"] + 0.897539542418026 * indata[u"PKA_260_ENG"] + -0.208281320974328 * indata[u"PKA_260_EXP"] + 0.877917725517767 * indata[u"PWY_R_HSA_1643685_CSV"] + -0.838104492145841 * indata[u"PWY_R_HSA_170834_EXP"] + -1.08810845812925 * indata[u"REC_R_HSA_198640"] + -0.345995888308396 * indata[u"SDOM_subdomainIV"] + -0.446748816655286 * indata[u"SFAM_DYRK1_EXP"] + 1.88660169350904 * indata[u"SFAM_FJ"] + 0.114907255276603 * indata[u"SFAM_FJ_EXP"]))

    H1_5 = tanh((18.6404160519433 + 0.363677355530911 * indata[u"EXP_ACVR2B"] + -0.133850110411448 * indata[u"EXP_SBK1"] + -2.69635443457946 * indata[u"EXP_SBK2"] + -0.544717661028514 * indata[u"EXP_STK10"] + -3.00445985724006 * indata[u"EXP_STK19"] + -1.79461100649895 * indata[u"GO_0060612"] + -3.21458438666107 * indata[u"GO_0061024"] + -2.70573670894486 * indata[u"MUT_GUCY2C"] + 2.08086333528751 * indata[u"MUT_RPS6KB2"] + 0.582471001015108 * indata[u"MUT_RPS6KB2_EXP"] + -1.0018275233064 * indata[u"MUT_TRPM6_EXP"] + 0.699295466341473 * indata[u"PKA_260_ENG"] + -0.503776528405347 * indata[u"PKA_260_EXP"] + 0.264808346682479 * indata[u"PWY_R_HSA_1643685_CSV"] + -0.503409756966692 * indata[u"PWY_R_HSA_170834_EXP"] + 2.553713621373 * indata[u"REC_R_HSA_198640"] + 0.340425777931837 * indata[u"SDOM_subdomainIV"] + 0.340411537191127 * indata[u"SFAM_DYRK1_EXP"] + 1.47577998035565 * indata[u"SFAM_FJ"] + 0.0551267041788375 * indata[u"SFAM_FJ_EXP"]))

    H1_6 = tanh((-1.36857527145823 + 0.188521845442329 * indata[u"EXP_ACVR2B"] + -0.456453542392897 * indata[u"EXP_SBK1"] + 5.06576678730646 * indata[u"EXP_SBK2"] + -1.79902733080704 * indata[u"EXP_STK10"] + -2.43500770263425 * indata[u"EXP_STK19"] + -0.0186762166214901 * indata[u"GO_0060612"] + 3.40133017700375 * indata[u"GO_0061024"] + 2.05124800368586 * indata[u"MUT_GUCY2C"] + 2.1699755433653 * indata[u"MUT_RPS6KB2"] + 0.0707665151362308 * indata[u"MUT_RPS6KB2_EXP"] + 0.339321105972709 * indata[u"MUT_TRPM6_EXP"] + -0.26526095986336 * indata[u"PKA_260_ENG"] + -0.372948365661251 * indata[u"PKA_260_EXP"] + 0.699311710547817 * indata[u"PWY_R_HSA_1643685_CSV"] + 0.300576922028288 * indata[u"PWY_R_HSA_170834_EXP"] + -0.228028752894373 * indata[u"REC_R_HSA_198640"] + -0.249174871544095 * indata[u"SDOM_subdomainIV"] + -0.329546442722344 * indata[u"SFAM_DYRK1_EXP"] + -1.54674365055832 * indata[u"SFAM_FJ"] + -0.119428458592626 * indata[u"SFAM_FJ_EXP"]))

    H1_7 = tanh((8.33278468544607 + 1.05697874412637 * indata[u"EXP_ACVR2B"] + -0.426831980966929 * indata[u"EXP_SBK1"] + -3.50981217882055 * indata[u"EXP_SBK2"] + -0.207839064084222 * indata[u"EXP_STK10"] + 1.07362835340488 * indata[u"EXP_STK19"] + -0.297608270069133 * indata[u"GO_0060612"] + -3.11109999412034 * indata[u"GO_0061024"] + -2.65480969693527 * indata[u"MUT_GUCY2C"] + -2.39892656244375 * indata[u"MUT_RPS6KB2"] + -0.00845585423301689 * indata[u"MUT_RPS6KB2_EXP"] + -0.214239243047732 * indata[u"MUT_TRPM6_EXP"] + 0.83526427364734 * indata[u"PKA_260_ENG"] + 0.162627360741503 * indata[u"PKA_260_EXP"] + -1.53009614765577 * indata[u"PWY_R_HSA_1643685_CSV"] + -0.0644772732315285 * indata[u"PWY_R_HSA_170834_EXP"] + 3.54664107253962 * indata[u"REC_R_HSA_198640"] + 0.0319701124609403 * indata[u"SDOM_subdomainIV"] + -0.000569910877050502 * indata[u"SFAM_DYRK1_EXP"] + 1.14942925094055 * indata[u"SFAM_FJ"] + 0.0951585945018385 * indata[u"SFAM_FJ_EXP"]))

    H1_8 = tanh((-24.6138886583587 + -0.153864462151973 * indata[u"EXP_ACVR2B"] + -0.401193905707168 * indata[u"EXP_SBK1"] + 3.78134730695969 * indata[u"EXP_SBK2"] + 0.946789871380108 * indata[u"EXP_STK10"] + 3.68299949580573 * indata[u"EXP_STK19"] + 0.628733938452901 * indata[u"GO_0060612"] + 1.21130658682087 * indata[u"GO_0061024"] + 0.897281187506358 * indata[u"MUT_GUCY2C"] + 0.437225501674806 * indata[u"MUT_RPS6KB2"] + -1.04564652647563 * indata[u"MUT_RPS6KB2_EXP"] + -0.109079333341285 * indata[u"MUT_TRPM6_EXP"] + -0.367555213173076 * indata[u"PKA_260_ENG"] + 0.208772617981407 * indata[u"PKA_260_EXP"] + -0.821525349368314 * indata[u"PWY_R_HSA_1643685_CSV"] + -0.583658463347237 * indata[u"PWY_R_HSA_170834_EXP"] + 0.595117553986068 * indata[u"REC_R_HSA_198640"] + 1.25904955464814 * indata[u"SDOM_subdomainIV"] + -0.451385356596753 * indata[u"SFAM_DYRK1_EXP"] + -0.181233633792015 * indata[u"SFAM_FJ"] + -0.349947396942806 * indata[u"SFAM_FJ_EXP"]))

    H1_9 = tanh((-18.5207803529792 + -0.21475185265707 * indata[u"EXP_ACVR2B"] + -0.766883703086602 * indata[u"EXP_SBK1"] + 5.34963522679384 * indata[u"EXP_SBK2"] + 0.823737923836906 * indata[u"EXP_STK10"] + 0.480551521442438 * indata[u"EXP_STK19"] + 2.10742451497407 * indata[u"GO_0060612"] + 1.61085510869649 * indata[u"GO_0061024"] + -2.75077301879856 * indata[u"MUT_GUCY2C"] + -0.69923174544656 * indata[u"MUT_RPS6KB2"] + -0.00137936230565482 * indata[u"MUT_RPS6KB2_EXP"] + 0.00641110237186359 * indata[u"MUT_TRPM6_EXP"] + -0.437955048779413 * indata[u"PKA_260_ENG"] + 0.406527301500715 * indata[u"PKA_260_EXP"] + -1.81116595671658 * indata[u"PWY_R_HSA_1643685_CSV"] + 0.145649249967572 * indata[u"PWY_R_HSA_170834_EXP"] + -0.833578314579727 * indata[u"REC_R_HSA_198640"] + -0.0426141550674002 * indata[u"SDOM_subdomainIV"] + 0.466902383293522 * indata[u"SFAM_DYRK1_EXP"] + 1.16965167779304 * indata[u"SFAM_FJ"] + -0.0199285296004546 * indata[u"SFAM_FJ_EXP"]))

    H1_10 = tanh((23.1582262362569 + -0.383609347385795 * indata[u"EXP_ACVR2B"] + -0.0901774224005553 * indata[u"EXP_SBK1"] + -4.20967684794272 * indata[u"EXP_SBK2"] + 0.110076408383235 * indata[u"EXP_STK10"] + -2.99593642116277 * indata[u"EXP_STK19"] + 2.88328591420978 * indata[u"GO_0060612"] + -0.446464742868819 * indata[u"GO_0061024"] + -0.884591666697556 * indata[u"MUT_GUCY2C"] + -0.0473387924886714 * indata[u"MUT_RPS6KB2"] + -0.475160222782998 * indata[u"MUT_RPS6KB2_EXP"] + -0.167806636265196 * indata[u"MUT_TRPM6_EXP"] + -0.516017658216096 * indata[u"PKA_260_ENG"] + 0.134097529314922 * indata[u"PKA_260_EXP"] + 0.897633027279649 * indata[u"PWY_R_HSA_1643685_CSV"] + -0.252555390825535 * indata[u"PWY_R_HSA_170834_EXP"] + 2.80028829105772 * indata[u"REC_R_HSA_198640"] + 0.058494906835196 * indata[u"SDOM_subdomainIV"] + -0.560969429244952 * indata[u"SFAM_DYRK1_EXP"] + 0.741801414985226 * indata[u"SFAM_FJ"] + -0.000572510239064283 * indata[u"SFAM_FJ_EXP"]))

    H1_11 = tanh((4.03168737398602 + 1.2002655842553 * indata[u"EXP_ACVR2B"] + -0.464810325113589 * indata[u"EXP_SBK1"] + -1.6229982514703 * indata[u"EXP_SBK2"] + -1.00993781891707 * indata[u"EXP_STK10"] + 0.838333686856118 * indata[u"EXP_STK19"] + 2.46156268710068 * indata[u"GO_0060612"] + -0.102934664171416 * indata[u"GO_0061024"] + -2.11435729879781 * indata[u"MUT_GUCY2C"] + -0.100654662261123 * indata[u"MUT_RPS6KB2"] + 1.04549890417495 * indata[u"MUT_RPS6KB2_EXP"] + -0.251662233954933 * indata[u"MUT_TRPM6_EXP"] + 0.404189987146484 * indata[u"PKA_260_ENG"] + -0.527830061781302 * indata[u"PKA_260_EXP"] + -0.380439971126057 * indata[u"PWY_R_HSA_1643685_CSV"] + -0.291926435789721 * indata[u"PWY_R_HSA_170834_EXP"] + 0.409769375206074 * indata[u"REC_R_HSA_198640"] + -0.616338343529825 * indata[u"SDOM_subdomainIV"] + -0.00360167440517029 * indata[u"SFAM_DYRK1_EXP"] + 2.80098016814932 * indata[u"SFAM_FJ"] + -0.206845191703064 * indata[u"SFAM_FJ_EXP"]))

    outdata[u"Predicted IC50_1"] = 2.75246985453205 + 0.873017431543742 * H1_1 + -0.832736641559363 * H1_10 + -0.158551042090897 * H1_11 + -0.814331322755219 * H1_2 + -0.34732485394107 * H1_3 + 0.164850998564721 * H1_4 + -0.0355000970750534 * H1_5 + -0.80485243721578 * H1_6 + -0.503873173409564 * H1_7 + 0.698629300295572 * H1_8 + -0.346502429994361 * H1_9

    return outdata[u"Predicted IC50_1"]


