library(glmnet)
mydata = read.table("./TrainingSet/RF/soft_tissue.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0.35,family="gaussian",standardize=TRUE)
sink('./Model/EN/Classifier/soft_tissue/soft_tissue_047.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
