from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """


def getInputMetadata():
    return {
        u"CLS_average_ploidy": "float",
        u"EXP_MAPK13_X_EXP_CARD9": "float",
        u"EXP_MAPK13_X_EXP_CDC42": "float",
        u"EXP_MAPK13_X_EXP_DSCAM": "float",
        u"EXP_MAPK13_X_EXP_FOSB": "float",
        u"EXP_MAPK13_X_EXP_FOXO3": "float",
        u"EXP_MAPK13_X_EXP_GNAI3": "float",
        u"EXP_MAPK13_X_EXP_GNB2": "float",
        u"EXP_MAPK13_X_EXP_RAPGEF4": "float",
        u"EXP_MAPK13_X_EXP_STMN1": "float",
        u"EXP_NEK6_X_EXP_NUP37": "float",
        u"EXP_NEK6_X_EXP_TOP2A": "float",
        u"EXP_PIM2": "float",
        u"EXP_STK16": "float",
        u"EXP_STK16_X_EXP_PEPD": "float",
        u"EXP_STK24_X_EXP_STRN3": "float",
        u"EXP_TRIM33": "float",
        u"Fingerprint_611": "float",
        u"Fingerprint_646": "float",
        u"Fingerprint_712": "float",
        u"Fingerprint_779": "float",
        u"Fingerprint_797": "float",
        u"Fingerprint_818": "float",
        u"GO_0007507_CSV_X_GO_0019233_CSV": "float",
        u"GO_0030878": "float",
        u"GO_0030878_EXP": "float",
        u"GO_0043114_EXP_X_GO_0045785_EXP": "float",
        u"GO_0043114_X_GO_0045785": "float",
        u"PKA_197_ENG_X_Fingerprint_818": "float",
        u"PKA_217_EXP_X_Fingerprint_818": "float",
        u"PWY_R_HSA_5663213_X_PWY_R_HSA_6798695": "float",
        u"REC_R_HSA_141409": "float",
        u"REC_R_HSA_5675194": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6

    H1_1 = tanh((-1.03291656809924 + 0.185768046583125 * indata[u"CLS_average_ploidy"] + 0.000128376345573195 * indata[u"EXP_MAPK13_X_EXP_CARD9"] + -0.000233241631936439 * indata[u"EXP_MAPK13_X_EXP_CDC42"] + -0.00108175876141159 * indata[u"EXP_MAPK13_X_EXP_DSCAM"] + -0.00228343130963738 * indata[u"EXP_MAPK13_X_EXP_FOSB"] + -0.00103252608974021 * indata[u"EXP_MAPK13_X_EXP_FOXO3"] + -0.000258235141474855 * indata[u"EXP_MAPK13_X_EXP_GNAI3"] + 0.000295473540341465 * indata[u"EXP_MAPK13_X_EXP_GNB2"] + 0.00302118309707078 * indata[u"EXP_MAPK13_X_EXP_RAPGEF4"] + 0.000266602097542272 * indata[u"EXP_MAPK13_X_EXP_STMN1"] + -0.003086126970139 * indata[u"EXP_NEK6_X_EXP_NUP37"] + -0.00883454439507131 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.00147043246761434 * indata[u"EXP_PIM2"] + -0.00143396677372395 * indata[u"EXP_STK16"] + -0.000476089572070861 * indata[u"EXP_STK16_X_EXP_PEPD"] + -0.00378670551451706 * indata[u"EXP_STK24_X_EXP_STRN3"] + 0.058146266164347 * indata[u"EXP_TRIM33"] + 2.70108602965327 * indata[u"Fingerprint_611"] + -0.573754695350515 * indata[u"Fingerprint_646"] + 0.669356347631897 * indata[u"Fingerprint_712"] + 0.196639978495452 * indata[u"Fingerprint_779"] + -2.44715691773696 * indata[u"Fingerprint_797"] + 0.0835360490695552 * indata[u"Fingerprint_818"] + 0.00810149054817845 * indata[u"GO_0007507_CSV_X_GO_0019233_CSV"] + 0.0253301072128394 * indata[u"GO_0030878"] + 0.000840108275006297 * indata[u"GO_0030878_EXP"] + 0.0000531111215320609 * indata[u"GO_0043114_EXP_X_GO_0045785_EXP"] + 0.0176708680595143 * indata[u"GO_0043114_X_GO_0045785"] + 0.862068756305008 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.000721905316231874 * indata[u"PKA_217_EXP_X_Fingerprint_818"] + 0.0073755037529316 * indata[u"PWY_R_HSA_5663213_X_PWY_R_HSA_6798695"] + -0.00661849274798449 * indata[u"REC_R_HSA_141409"] + -0.0165827092875762 * indata[u"REC_R_HSA_5675194"]))

    H1_2 = tanh((-0.218604058006307 + -0.00087066609131946 * indata[u"CLS_average_ploidy"] + 0.000917662070896704 * indata[u"EXP_MAPK13_X_EXP_CARD9"] + -0.00270041565702743 * indata[u"EXP_MAPK13_X_EXP_CDC42"] + 0.0000082296965307056 * indata[u"EXP_MAPK13_X_EXP_DSCAM"] + -0.000256099747475623 * indata[u"EXP_MAPK13_X_EXP_FOSB"] + -0.00221575422584704 * indata[u"EXP_MAPK13_X_EXP_FOXO3"] + -0.00015997768533915 * indata[u"EXP_MAPK13_X_EXP_GNAI3"] + 0.000342191134306542 * indata[u"EXP_MAPK13_X_EXP_GNB2"] + 0.000360904982854365 * indata[u"EXP_MAPK13_X_EXP_RAPGEF4"] + -0.0000020711240841545 * indata[u"EXP_MAPK13_X_EXP_STMN1"] + 0.000904286372715782 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.00178386705468723 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + 0.0164476200336388 * indata[u"EXP_PIM2"] + 0.0273238137241066 * indata[u"EXP_STK16"] + 0.00127977770153894 * indata[u"EXP_STK16_X_EXP_PEPD"] + 0.00689301296981505 * indata[u"EXP_STK24_X_EXP_STRN3"] + 0.00147182920863272 * indata[u"EXP_TRIM33"] + -2.46695839709976 * indata[u"Fingerprint_611"] + 1.94946700265492 * indata[u"Fingerprint_646"] + 0.20771859038117 * indata[u"Fingerprint_712"] + -1.02242653083577 * indata[u"Fingerprint_779"] + -0.0379625713750633 * indata[u"Fingerprint_797"] + 1.03073722825535 * indata[u"Fingerprint_818"] + -0.00270544620494138 * indata[u"GO_0007507_CSV_X_GO_0019233_CSV"] + -0.00898232278871643 * indata[u"GO_0030878"] + 0.000408461055987181 * indata[u"GO_0030878_EXP"] + -0.000777429206078939 * indata[u"GO_0043114_EXP_X_GO_0045785_EXP"] + -0.0137865570796785 * indata[u"GO_0043114_X_GO_0045785"] + -0.314340170212291 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + -0.170381515867635 * indata[u"PKA_217_EXP_X_Fingerprint_818"] + -0.0152745364527577 * indata[u"PWY_R_HSA_5663213_X_PWY_R_HSA_6798695"] + 0.0367112146044594 * indata[u"REC_R_HSA_141409"] + 0.00969169127516258 * indata[u"REC_R_HSA_5675194"]))

    H1_3 = tanh((-0.871308778868807 + 0.100199016557462 * indata[u"CLS_average_ploidy"] + -0.0129245983488042 * indata[u"EXP_MAPK13_X_EXP_CARD9"] + -0.0120420241163693 * indata[u"EXP_MAPK13_X_EXP_CDC42"] + -0.00267285650880441 * indata[u"EXP_MAPK13_X_EXP_DSCAM"] + -0.00179934308902818 * indata[u"EXP_MAPK13_X_EXP_FOSB"] + -0.0000275131225713979 * indata[u"EXP_MAPK13_X_EXP_FOXO3"] + 0.0000449164732285742 * indata[u"EXP_MAPK13_X_EXP_GNAI3"] + -0.00229679650185726 * indata[u"EXP_MAPK13_X_EXP_GNB2"] + -0.0791854104770086 * indata[u"EXP_MAPK13_X_EXP_RAPGEF4"] + -0.000310859641952256 * indata[u"EXP_MAPK13_X_EXP_STMN1"] + 0.000334944291588527 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.00170201808397979 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.325540637877753 * indata[u"EXP_PIM2"] + 0.0903094728949827 * indata[u"EXP_STK16"] + -0.0327253166090438 * indata[u"EXP_STK16_X_EXP_PEPD"] + -0.00616518883093439 * indata[u"EXP_STK24_X_EXP_STRN3"] + 0.459555486197345 * indata[u"EXP_TRIM33"] + 1.03294364616909 * indata[u"Fingerprint_611"] + 0.759625166155314 * indata[u"Fingerprint_646"] + 0.700728003285816 * indata[u"Fingerprint_712"] + 0.833146905834955 * indata[u"Fingerprint_779"] + -1.24285608216533 * indata[u"Fingerprint_797"] + 0.196004974697427 * indata[u"Fingerprint_818"] + -0.140670429091213 * indata[u"GO_0007507_CSV_X_GO_0019233_CSV"] + 0.00223426719656679 * indata[u"GO_0030878"] + -0.000123895599741812 * indata[u"GO_0030878_EXP"] + -0.000280584921889916 * indata[u"GO_0043114_EXP_X_GO_0045785_EXP"] + -0.000648974385241954 * indata[u"GO_0043114_X_GO_0045785"] + 0.00391329259493605 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.0168247488403534 * indata[u"PKA_217_EXP_X_Fingerprint_818"] + 0.345819377987187 * indata[u"PWY_R_HSA_5663213_X_PWY_R_HSA_6798695"] + 0.0299364656502858 * indata[u"REC_R_HSA_141409"] + -0.089504986340215 * indata[u"REC_R_HSA_5675194"]))

    H1_4 = tanh((-1.43729063039998 + 0.00548696311131783 * indata[u"CLS_average_ploidy"] + -0.00273665541386201 * indata[u"EXP_MAPK13_X_EXP_CARD9"] + -0.033688915656113 * indata[u"EXP_MAPK13_X_EXP_CDC42"] + -0.0453261059324977 * indata[u"EXP_MAPK13_X_EXP_DSCAM"] + -0.00468991756938902 * indata[u"EXP_MAPK13_X_EXP_FOSB"] + -0.000941206854860861 * indata[u"EXP_MAPK13_X_EXP_FOXO3"] + -0.00140892116733555 * indata[u"EXP_MAPK13_X_EXP_GNAI3"] + -0.00270358917618414 * indata[u"EXP_MAPK13_X_EXP_GNB2"] + -0.00818293239472631 * indata[u"EXP_MAPK13_X_EXP_RAPGEF4"] + -0.00240671152527402 * indata[u"EXP_MAPK13_X_EXP_STMN1"] + 0.00921909946132678 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.0311364729304304 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.0516161654544354 * indata[u"EXP_PIM2"] + -0.0120390793695388 * indata[u"EXP_STK16"] + -0.01830605989483 * indata[u"EXP_STK16_X_EXP_PEPD"] + -0.0136008619403994 * indata[u"EXP_STK24_X_EXP_STRN3"] + 0.413413702257338 * indata[u"EXP_TRIM33"] + -0.774015311637827 * indata[u"Fingerprint_611"] + -0.431267566344933 * indata[u"Fingerprint_646"] + -0.629048475870261 * indata[u"Fingerprint_712"] + 0.928367703744677 * indata[u"Fingerprint_779"] + -1.19112614646235 * indata[u"Fingerprint_797"] + -0.752768510083831 * indata[u"Fingerprint_818"] + -0.0190965256747207 * indata[u"GO_0007507_CSV_X_GO_0019233_CSV"] + 0.0422548222024564 * indata[u"GO_0030878"] + -0.000386885828709436 * indata[u"GO_0030878_EXP"] + 0.00771615780030475 * indata[u"GO_0043114_EXP_X_GO_0045785_EXP"] + -0.0137861967962299 * indata[u"GO_0043114_X_GO_0045785"] + 0.0252360337752403 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.123977158615177 * indata[u"PKA_217_EXP_X_Fingerprint_818"] + 0.402607283066055 * indata[u"PWY_R_HSA_5663213_X_PWY_R_HSA_6798695"] + 0.0109261714971989 * indata[u"REC_R_HSA_141409"] + -0.0100478152412234 * indata[u"REC_R_HSA_5675194"]))

    H1_5 = tanh((0.816839388204569 + 0.0887092904721192 * indata[u"CLS_average_ploidy"] + 0.00524879299675563 * indata[u"EXP_MAPK13_X_EXP_CARD9"] + 0.000703460025188175 * indata[u"EXP_MAPK13_X_EXP_CDC42"] + 0.00400063322432731 * indata[u"EXP_MAPK13_X_EXP_DSCAM"] + 0.00151873269303157 * indata[u"EXP_MAPK13_X_EXP_FOSB"] + 0.000704716854428691 * indata[u"EXP_MAPK13_X_EXP_FOXO3"] + 0.000849823683650672 * indata[u"EXP_MAPK13_X_EXP_GNAI3"] + 0.00172666783668881 * indata[u"EXP_MAPK13_X_EXP_GNB2"] + 0.0035359610148698 * indata[u"EXP_MAPK13_X_EXP_RAPGEF4"] + 0.000757772085159123 * indata[u"EXP_MAPK13_X_EXP_STMN1"] + -0.00721257171666344 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.00243083322479462 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + -0.188179576806748 * indata[u"EXP_PIM2"] + -0.00597270041740714 * indata[u"EXP_STK16"] + -0.00016925615856242 * indata[u"EXP_STK16_X_EXP_PEPD"] + 0.00861851024118924 * indata[u"EXP_STK24_X_EXP_STRN3"] + -0.0108954524957608 * indata[u"EXP_TRIM33"] + 0.353455292340922 * indata[u"Fingerprint_611"] + -0.318869076876131 * indata[u"Fingerprint_646"] + -0.38409868816011 * indata[u"Fingerprint_712"] + -1.67039668597161 * indata[u"Fingerprint_779"] + -0.514622291453516 * indata[u"Fingerprint_797"] + 2.05921967075293 * indata[u"Fingerprint_818"] + -0.254418166412974 * indata[u"GO_0007507_CSV_X_GO_0019233_CSV"] + 0.000430087094958884 * indata[u"GO_0030878"] + -0.00177726381031265 * indata[u"GO_0030878_EXP"] + -0.00609012195340722 * indata[u"GO_0043114_EXP_X_GO_0045785_EXP"] + -0.125103628551486 * indata[u"GO_0043114_X_GO_0045785"] + 0.0402808013834826 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + 0.000376201620652883 * indata[u"PKA_217_EXP_X_Fingerprint_818"] + -0.0109429288924268 * indata[u"PWY_R_HSA_5663213_X_PWY_R_HSA_6798695"] + -0.0333122609983504 * indata[u"REC_R_HSA_141409"] + 0.0148912349568052 * indata[u"REC_R_HSA_5675194"]))

    H1_6 = tanh((-0.182275755116934 + 0.0550958151567689 * indata[u"CLS_average_ploidy"] + -0.00331646411809549 * indata[u"EXP_MAPK13_X_EXP_CARD9"] + -0.000500039671183657 * indata[u"EXP_MAPK13_X_EXP_CDC42"] + -0.00246715383152149 * indata[u"EXP_MAPK13_X_EXP_DSCAM"] + -0.000411607618386634 * indata[u"EXP_MAPK13_X_EXP_FOSB"] + -0.000240916809440172 * indata[u"EXP_MAPK13_X_EXP_FOXO3"] + 0.0000013155768867177 * indata[u"EXP_MAPK13_X_EXP_GNAI3"] + 0.000608349512760541 * indata[u"EXP_MAPK13_X_EXP_GNB2"] + -0.00231178737534867 * indata[u"EXP_MAPK13_X_EXP_RAPGEF4"] + -0.000734425264632521 * indata[u"EXP_MAPK13_X_EXP_STMN1"] + 0.0023457824806755 * indata[u"EXP_NEK6_X_EXP_NUP37"] + 0.0100690091353557 * indata[u"EXP_NEK6_X_EXP_TOP2A"] + 0.0958341565337928 * indata[u"EXP_PIM2"] + -0.016258872082057 * indata[u"EXP_STK16"] + -0.00647044324082301 * indata[u"EXP_STK16_X_EXP_PEPD"] + 0.0208039378393857 * indata[u"EXP_STK24_X_EXP_STRN3"] + -0.00208347216169032 * indata[u"EXP_TRIM33"] + -0.896235011958427 * indata[u"Fingerprint_611"] + -0.398107084478428 * indata[u"Fingerprint_646"] + -1.18121897694757 * indata[u"Fingerprint_712"] + -1.65838230358895 * indata[u"Fingerprint_779"] + -1.14116099962064 * indata[u"Fingerprint_797"] + 1.68107968342393 * indata[u"Fingerprint_818"] + -0.000631685928596524 * indata[u"GO_0007507_CSV_X_GO_0019233_CSV"] + 0.00907888340329244 * indata[u"GO_0030878"] + -0.000514125755455024 * indata[u"GO_0030878_EXP"] + -0.000323566173782842 * indata[u"GO_0043114_EXP_X_GO_0045785_EXP"] + -0.000259656043044737 * indata[u"GO_0043114_X_GO_0045785"] + 0.0403057455968334 * indata[u"PKA_197_ENG_X_Fingerprint_818"] + -0.0100366221925341 * indata[u"PKA_217_EXP_X_Fingerprint_818"] + 0.0476716234699432 * indata[u"PWY_R_HSA_5663213_X_PWY_R_HSA_6798695"] + 0.0181636691897597 * indata[u"REC_R_HSA_141409"] + 0.0549326398824558 * indata[u"REC_R_HSA_5675194"]))

    outdata[u"Predicted IC50_1"] = 2.19993762680707 + 2.30738607355514 * H1_1 + 2.30769352875441 * H1_2 + -2.60279520823358 * H1_3 + 2.55300942092367 * H1_4 + 1.91267993254207 * H1_5 + -3.11400229024488 * H1_6

    return outdata[u"Predicted IC50_1"]


