from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """


def getInputMetadata():
    return {
        u"EXP_CDKL5": "float",
        u"EXP_CLK4": "float",
        u"EXP_PLK3": "float",
        u"EXP_PLK3_X_EXP_CDC14B": "float",
        u"EXP_PLK3_X_EXP_CDC27": "float",
        u"EXP_PLK3_X_EXP_PTEN": "float",
        u"EXP_PLK3_X_EXP_RAD21": "float",
        u"EXP_PLK3_X_EXP_YWHAH": "float",
        u"EXP_PRKCG": "float",
        u"EXP_PRKCG_X_EXP_GNAI3": "float",
        u"EXP_PRKCG_X_EXP_GNG8": "float",
        u"EXP_PRKCG_X_EXP_PLCB3": "float",
        u"EXP_PRKCG_X_EXP_SLC9A1": "float",
        u"EXP_PRKCG_X_EXP_TRPV4": "float",
        u"EXP_SGK2": "float",
        u"EXP_SGK2_X_EXP_UBC": "float",
        u"EXP_SLK": "float",
        u"EXP_STK10": "float",
        u"EXP_TLK1": "float",
        u"EXP_TLK1_X_EXP_ASF1A": "float",
        u"Fingerprint_646": "float",
        u"Fingerprint_677": "float",
        u"Fingerprint_686": "float",
        u"Fingerprint_710": "float",
        u"Fingerprint_712": "float",
        u"Fingerprint_797": "float",
        u"Fingerprint_818": "float",
        u"From_Sanger": "float",
        u"GO_0034976": "float",
        u"PKA_190_EXP": "float",
        u"PWY_R_HSA_2682334_EXP_X_PWY_R_HSA_416476_EXP": "float",
        u"PWY_R_HSA_2682334_X_PWY_R_HSA_416476": "float",
        u"REC_R_HSA_199839": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6

    H1_1 = tanh((1.23063472735301 + -0.0400695411487648 * indata[u"EXP_CDKL5"] + 0.136336894933094 * indata[u"EXP_CLK4"] + -0.00422899049654803 * indata[u"EXP_PLK3"] + -0.00187731640645189 * indata[u"EXP_PLK3_X_EXP_CDC14B"] + -0.000409654418439286 * indata[u"EXP_PLK3_X_EXP_CDC27"] + 0.000579722136598382 * indata[u"EXP_PLK3_X_EXP_PTEN"] + -0.000448563357924272 * indata[u"EXP_PLK3_X_EXP_RAD21"] + -0.00610743738757146 * indata[u"EXP_PLK3_X_EXP_YWHAH"] + -0.248497159442591 * indata[u"EXP_PRKCG"] + -0.00394290910960934 * indata[u"EXP_PRKCG_X_EXP_GNAI3"] + -0.0051008504841728 * indata[u"EXP_PRKCG_X_EXP_GNG8"] + 0.00439944722981669 * indata[u"EXP_PRKCG_X_EXP_PLCB3"] + -0.00193604892583023 * indata[u"EXP_PRKCG_X_EXP_SLC9A1"] + 0.0514300734746372 * indata[u"EXP_PRKCG_X_EXP_TRPV4"] + -0.0279879741189278 * indata[u"EXP_SGK2"] + -0.00535000435860198 * indata[u"EXP_SGK2_X_EXP_UBC"] + -0.00268275422009555 * indata[u"EXP_SLK"] + 0.0513350029735752 * indata[u"EXP_STK10"] + -0.0869623154106247 * indata[u"EXP_TLK1"] + -0.00710230909565994 * indata[u"EXP_TLK1_X_EXP_ASF1A"] + 0.861503171305392 * indata[u"Fingerprint_646"] + -0.145609248368126 * indata[u"Fingerprint_677"] + 1.19663295997794 * indata[u"Fingerprint_686"] + 0.0628695415021934 * indata[u"Fingerprint_710"] + 1.49176601881482 * indata[u"Fingerprint_712"] + 0.682951891182114 * indata[u"Fingerprint_797"] + -4.53640739561276 * indata[u"Fingerprint_818"] + -0.238528585845202 * indata[u"From_Sanger"] + -0.0810554585543812 * indata[u"GO_0034976"] + -0.0660680245820635 * indata[u"PKA_190_EXP"] + -0.000808353319150965 * indata[u"PWY_R_HSA_2682334_EXP_X_PWY_R_HSA_416476_EXP"] + -0.130898463391503 * indata[u"PWY_R_HSA_2682334_X_PWY_R_HSA_416476"] + -0.00122013018282048 * indata[u"REC_R_HSA_199839"]))

    H1_2 = tanh((11.1959364726606 + -0.258617544864503 * indata[u"EXP_CDKL5"] + 0.0495834193355869 * indata[u"EXP_CLK4"] + -0.0318748025249481 * indata[u"EXP_PLK3"] + -0.00302960037841145 * indata[u"EXP_PLK3_X_EXP_CDC14B"] + 0.0000100457078900059 * indata[u"EXP_PLK3_X_EXP_CDC27"] + 0.00330448007498776 * indata[u"EXP_PLK3_X_EXP_PTEN"] + -0.00140197008859734 * indata[u"EXP_PLK3_X_EXP_RAD21"] + 0.0000565947622389142 * indata[u"EXP_PLK3_X_EXP_YWHAH"] + 0.0118320381613409 * indata[u"EXP_PRKCG"] + -0.000850613006575991 * indata[u"EXP_PRKCG_X_EXP_GNAI3"] + -0.118777050484141 * indata[u"EXP_PRKCG_X_EXP_GNG8"] + -0.381821211678274 * indata[u"EXP_PRKCG_X_EXP_PLCB3"] + 0.00247945256351681 * indata[u"EXP_PRKCG_X_EXP_SLC9A1"] + -0.15286951550516 * indata[u"EXP_PRKCG_X_EXP_TRPV4"] + -0.220984052096665 * indata[u"EXP_SGK2"] + -0.00320791183417103 * indata[u"EXP_SGK2_X_EXP_UBC"] + 0.0148623942063777 * indata[u"EXP_SLK"] + -0.00965080253514567 * indata[u"EXP_STK10"] + -0.106870832842509 * indata[u"EXP_TLK1"] + -0.00237641528259985 * indata[u"EXP_TLK1_X_EXP_ASF1A"] + 0.148768354999476 * indata[u"Fingerprint_646"] + 0.141357342196673 * indata[u"Fingerprint_677"] + -0.184601577857646 * indata[u"Fingerprint_686"] + -0.11668696289125 * indata[u"Fingerprint_710"] + -0.601873085519914 * indata[u"Fingerprint_712"] + 0.0165304225416618 * indata[u"Fingerprint_797"] + 0.0945444707962606 * indata[u"Fingerprint_818"] + -1.59427687304618 * indata[u"From_Sanger"] + 0.05076771587744 * indata[u"GO_0034976"] + 0.0302224397106743 * indata[u"PKA_190_EXP"] + -0.00262238503733784 * indata[u"PWY_R_HSA_2682334_EXP_X_PWY_R_HSA_416476_EXP"] + -0.000870381990593109 * indata[u"PWY_R_HSA_2682334_X_PWY_R_HSA_416476"] + 0.12316209543422 * indata[u"REC_R_HSA_199839"]))

    H1_3 = tanh((-1.00439937145881 + 0.000223226847044693 * indata[u"EXP_CDKL5"] + 0.0689534330864089 * indata[u"EXP_CLK4"] + -0.0148980962519196 * indata[u"EXP_PLK3"] + 0.0000334141852069478 * indata[u"EXP_PLK3_X_EXP_CDC14B"] + -0.000549039674084159 * indata[u"EXP_PLK3_X_EXP_CDC27"] + -0.00192194457358555 * indata[u"EXP_PLK3_X_EXP_PTEN"] + -0.00294341332894188 * indata[u"EXP_PLK3_X_EXP_RAD21"] + -0.000111652511925095 * indata[u"EXP_PLK3_X_EXP_YWHAH"] + -0.0343495698759647 * indata[u"EXP_PRKCG"] + 0.0000553582988571868 * indata[u"EXP_PRKCG_X_EXP_GNAI3"] + -0.0000615941319551127 * indata[u"EXP_PRKCG_X_EXP_GNG8"] + -0.0105031317274763 * indata[u"EXP_PRKCG_X_EXP_PLCB3"] + -0.00241626407769994 * indata[u"EXP_PRKCG_X_EXP_SLC9A1"] + 0.0097026020285777 * indata[u"EXP_PRKCG_X_EXP_TRPV4"] + 0.300864347897922 * indata[u"EXP_SGK2"] + 0.00369748629444917 * indata[u"EXP_SGK2_X_EXP_UBC"] + 0.00306840919448081 * indata[u"EXP_SLK"] + 0.00112645120510863 * indata[u"EXP_STK10"] + 0.0116275929874509 * indata[u"EXP_TLK1"] + -0.00504285657300078 * indata[u"EXP_TLK1_X_EXP_ASF1A"] + 1.67149569280608 * indata[u"Fingerprint_646"] + 0.731380217804531 * indata[u"Fingerprint_677"] + -0.327807322416467 * indata[u"Fingerprint_686"] + -0.383926617307284 * indata[u"Fingerprint_710"] + -0.232268531600286 * indata[u"Fingerprint_712"] + 1.08903679711663 * indata[u"Fingerprint_797"] + -1.01605547162813 * indata[u"Fingerprint_818"] + -1.40619593760793 * indata[u"From_Sanger"] + -0.0219717358562802 * indata[u"GO_0034976"] + -0.0278007801912105 * indata[u"PKA_190_EXP"] + 0.000437369170410707 * indata[u"PWY_R_HSA_2682334_EXP_X_PWY_R_HSA_416476_EXP"] + 0.000061907718340156 * indata[u"PWY_R_HSA_2682334_X_PWY_R_HSA_416476"] + 0.0166552446947806 * indata[u"REC_R_HSA_199839"]))

    H1_4 = tanh((0.922422573369701 + -0.245866670997232 * indata[u"EXP_CDKL5"] + -0.0251573194027696 * indata[u"EXP_CLK4"] + 0.00869815619246608 * indata[u"EXP_PLK3"] + -0.00131193795823931 * indata[u"EXP_PLK3_X_EXP_CDC14B"] + 0.0000647591009151776 * indata[u"EXP_PLK3_X_EXP_CDC27"] + 0.00398767990657029 * indata[u"EXP_PLK3_X_EXP_PTEN"] + -0.0000791148039256735 * indata[u"EXP_PLK3_X_EXP_RAD21"] + 0.000641378966092158 * indata[u"EXP_PLK3_X_EXP_YWHAH"] + -0.151906014108449 * indata[u"EXP_PRKCG"] + 0.0000921376352788024 * indata[u"EXP_PRKCG_X_EXP_GNAI3"] + -0.00288180850948445 * indata[u"EXP_PRKCG_X_EXP_GNG8"] + -0.000234864058205501 * indata[u"EXP_PRKCG_X_EXP_PLCB3"] + -0.00759791022672209 * indata[u"EXP_PRKCG_X_EXP_SLC9A1"] + -0.103524049912445 * indata[u"EXP_PRKCG_X_EXP_TRPV4"] + 0.117408310360201 * indata[u"EXP_SGK2"] + 0.000455731330199982 * indata[u"EXP_SGK2_X_EXP_UBC"] + 0.0597959836020364 * indata[u"EXP_SLK"] + 0.0194557896670939 * indata[u"EXP_STK10"] + -0.0469960600701743 * indata[u"EXP_TLK1"] + 0.000480667874974527 * indata[u"EXP_TLK1_X_EXP_ASF1A"] + -0.116813743287564 * indata[u"Fingerprint_646"] + 0.0598150591837292 * indata[u"Fingerprint_677"] + 0.0267081335897165 * indata[u"Fingerprint_686"] + -0.589299381449233 * indata[u"Fingerprint_710"] + 1.19904659080603 * indata[u"Fingerprint_712"] + 1.07435078462775 * indata[u"Fingerprint_797"] + 0.538859065317108 * indata[u"Fingerprint_818"] + 1.27448953144615 * indata[u"From_Sanger"] + 0.0347822799670811 * indata[u"GO_0034976"] + 0.00803969830779111 * indata[u"PKA_190_EXP"] + -0.0000748357209984596 * indata[u"PWY_R_HSA_2682334_EXP_X_PWY_R_HSA_416476_EXP"] + -0.000474193631566242 * indata[u"PWY_R_HSA_2682334_X_PWY_R_HSA_416476"] + 0.00495730042652383 * indata[u"REC_R_HSA_199839"]))

    H1_5 = tanh((4.98677908886769 + -0.00570339041456113 * indata[u"EXP_CDKL5"] + 0.12702132806718 * indata[u"EXP_CLK4"] + -0.0662636824925526 * indata[u"EXP_PLK3"] + 0.0000352594061645365 * indata[u"EXP_PLK3_X_EXP_CDC14B"] + 0.00172609964957344 * indata[u"EXP_PLK3_X_EXP_CDC27"] + 0.0026997367327813 * indata[u"EXP_PLK3_X_EXP_PTEN"] + -0.00054866038741065 * indata[u"EXP_PLK3_X_EXP_RAD21"] + -0.0120340449751288 * indata[u"EXP_PLK3_X_EXP_YWHAH"] + -0.0404280509673878 * indata[u"EXP_PRKCG"] + -0.00085684249722461 * indata[u"EXP_PRKCG_X_EXP_GNAI3"] + -0.0142021059936692 * indata[u"EXP_PRKCG_X_EXP_GNG8"] + -0.240299013100787 * indata[u"EXP_PRKCG_X_EXP_PLCB3"] + 0.000297256094420939 * indata[u"EXP_PRKCG_X_EXP_SLC9A1"] + 0.0165380444336936 * indata[u"EXP_PRKCG_X_EXP_TRPV4"] + -0.0395537786840334 * indata[u"EXP_SGK2"] + -0.0292682849164727 * indata[u"EXP_SGK2_X_EXP_UBC"] + 0.000598481602065898 * indata[u"EXP_SLK"] + -0.0171494598430498 * indata[u"EXP_STK10"] + -0.078964177901386 * indata[u"EXP_TLK1"] + -0.0121351087123629 * indata[u"EXP_TLK1_X_EXP_ASF1A"] + 0.450365890968006 * indata[u"Fingerprint_646"] + 0.00381275902885431 * indata[u"Fingerprint_677"] + 0.0477044812441137 * indata[u"Fingerprint_686"] + 1.35200285574625 * indata[u"Fingerprint_710"] + -0.686540261773449 * indata[u"Fingerprint_712"] + -0.410947792565703 * indata[u"Fingerprint_797"] + -0.284964811539019 * indata[u"Fingerprint_818"] + 0.54035026359886 * indata[u"From_Sanger"] + -0.00362895209428891 * indata[u"GO_0034976"] + -0.00257228141985824 * indata[u"PKA_190_EXP"] + -0.00567153247127327 * indata[u"PWY_R_HSA_2682334_EXP_X_PWY_R_HSA_416476_EXP"] + -0.344639380996377 * indata[u"PWY_R_HSA_2682334_X_PWY_R_HSA_416476"] + 0.00745730977679866 * indata[u"REC_R_HSA_199839"]))

    H1_6 = tanh((-0.926761681816067 + -0.0249602649906825 * indata[u"EXP_CDKL5"] + -0.0448854719891807 * indata[u"EXP_CLK4"] + 0.00286906394208567 * indata[u"EXP_PLK3"] + 0.000188373615274917 * indata[u"EXP_PLK3_X_EXP_CDC14B"] + 0.00131132938872767 * indata[u"EXP_PLK3_X_EXP_CDC27"] + -0.00590988133741101 * indata[u"EXP_PLK3_X_EXP_PTEN"] + 0.0000679559449402259 * indata[u"EXP_PLK3_X_EXP_RAD21"] + 0.0000048312534575078 * indata[u"EXP_PLK3_X_EXP_YWHAH"] + 0.0467106113423684 * indata[u"EXP_PRKCG"] + 0.00518732824759748 * indata[u"EXP_PRKCG_X_EXP_GNAI3"] + 0.00253721523093065 * indata[u"EXP_PRKCG_X_EXP_GNG8"] + 0.00592331640789811 * indata[u"EXP_PRKCG_X_EXP_PLCB3"] + -0.00832179773402468 * indata[u"EXP_PRKCG_X_EXP_SLC9A1"] + -0.000674539421827227 * indata[u"EXP_PRKCG_X_EXP_TRPV4"] + -0.183013121246149 * indata[u"EXP_SGK2"] + -0.0053783960388535 * indata[u"EXP_SGK2_X_EXP_UBC"] + 0.0098112178470954 * indata[u"EXP_SLK"] + -0.0393713045108386 * indata[u"EXP_STK10"] + 0.0120645736917993 * indata[u"EXP_TLK1"] + 0.00229908578448501 * indata[u"EXP_TLK1_X_EXP_ASF1A"] + 0.689289007592956 * indata[u"Fingerprint_646"] + 0.0327146537539269 * indata[u"Fingerprint_677"] + -0.0904305305491733 * indata[u"Fingerprint_686"] + 1.04417572660325 * indata[u"Fingerprint_710"] + -0.228760485134741 * indata[u"Fingerprint_712"] + 0.642843262771762 * indata[u"Fingerprint_797"] + 0.984370000267507 * indata[u"Fingerprint_818"] + 0.8069633628721 * indata[u"From_Sanger"] + 0.0130019450476551 * indata[u"GO_0034976"] + -0.0117586700695911 * indata[u"PKA_190_EXP"] + 0.00189288891754097 * indata[u"PWY_R_HSA_2682334_EXP_X_PWY_R_HSA_416476_EXP"] + 0.00098588210885781 * indata[u"PWY_R_HSA_2682334_X_PWY_R_HSA_416476"] + -0.0609342582670378 * indata[u"REC_R_HSA_199839"]))

    outdata[u"Predicted IC50_1"] = 2.17491280635791 + 2.58036415418354 * H1_1 + 2.47075015357676 * H1_2 + -3.37940154006713 * H1_3 + -3.03329721089273 * H1_4 + -2.51384923147352 * H1_5 + 3.28876046461328 * H1_6

    return outdata[u"Predicted IC50_1"]


