library(glmnet)
mydata = read.table("./TrainingSet/Correlation/NSCLC.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=0.4,family="gaussian",standardize=TRUE)
sink('./Model/EN/Correlation/NSCLC/NSCLC_049.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
