library(glmnet)
mydata = read.table("./TrainingSet/LassoBIC/upper_aerodigestive_tract.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0.8,family="gaussian",standardize=TRUE)
sink('./Model/EN/Lasso/upper_aerodigestive_tract/upper_aerodigestive_tract_083.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
