from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """

def getModelMetadata():
	return {"creator": u"Neural", "modelName": u"", "predicted": u"IC50", "table": u"large_intestine", "version": u"14.1.0", "timestamp": u"2019-07-26T13:48:33Z"}


def getInputMetadata():
    return {
        u"DOM_Kringle_EXP": "float",
        u"EXP_MKNK1": "float",
        u"EXP_NUAK2": "float",
        u"EXP_TEC": "float",
        u"GO_0003222_CSV": "float",
        u"GO_0009791_CSV": "float",
        u"GO_0032880_EXP": "float",
        u"GO_0042733_EXP": "float",
        u"GO_0048536_CSV": "float",
        u"MOT_2D_beta8strand_CSV": "float",
        u"MUT_TSSK6": "float",
        u"PKA_113_D": "float",
        u"PKA_113_D_CSV": "float",
        u"PKA_124_POL": "float",
        u"PKA_129_S": "float",
        u"PKA_129_S_CSV": "float",
        u"PKA_129_S_EXP": "float",
        u"PKA_142": "float",
        u"PKA_164_ASA": "float",
        u"PKA_271_HYD": "float",
        u"PKA_272_M_CSV": "float",
        u"PWY_R_HSA_5689880_CSV": "float",
        u"PWY_R_HSA_8953750_EXP": "float",
        u"REC_R_HSA_2984220_CSV": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6
    # H1_7
    # H1_8
    # H1_9
    # H1_10
    # H1_11
    # H1_12

    H1_1 = tanh((-16.1870919859561 + -1.03987836871208 * indata[u"DOM_Kringle_EXP"] + 2.57045187340651 * indata[u"EXP_MKNK1"] + 1.29394772853784 * indata[u"EXP_NUAK2"] + 0.339273670465956 * indata[u"EXP_TEC"] + 2.20320119557239 * indata[u"GO_0003222_CSV"] + 1.93462081591712 * indata[u"GO_0009791_CSV"] + -0.358190480810574 * indata[u"GO_0032880_EXP"] + -0.225272825298211 * indata[u"GO_0042733_EXP"] + -1.44062196057305 * indata[u"GO_0048536_CSV"] + -0.650047545046691 * indata[u"MOT_2D_beta8strand_CSV"] + 0.515444590239556 * indata[u"MUT_TSSK6"] + -0.320725101331387 * indata[u"PKA_113_D"] + 4.14081227003776 * indata[u"PKA_113_D_CSV"] + 0.731724782180574 * indata[u"PKA_124_POL"] + -2.72744932526874 * indata[u"PKA_129_S"] + -1.09746570556919 * indata[u"PKA_129_S_CSV"] + 0.28662059741786 * indata[u"PKA_129_S_EXP"] + 0.648601492961075 * indata[u"PKA_142"] + -0.0876444920131729 * indata[u"PKA_164_ASA"] + -0.898074983867203 * indata[u"PKA_271_HYD"] + 15.5532396372683 * indata[u"PKA_272_M_CSV"] + 2.65159512578952 * indata[u"PWY_R_HSA_5689880_CSV"] + -0.372638828108583 * indata[u"PWY_R_HSA_8953750_EXP"] + 6.5402622023226 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_2 = tanh((-23.3063562163916 + 0.366499657079662 * indata[u"DOM_Kringle_EXP"] + 5.07297522235348 * indata[u"EXP_MKNK1"] + 1.33468824573576 * indata[u"EXP_NUAK2"] + -0.831132724690335 * indata[u"EXP_TEC"] + -3.08633993788344 * indata[u"GO_0003222_CSV"] + -1.60172902883629 * indata[u"GO_0009791_CSV"] + 0.666036913701147 * indata[u"GO_0032880_EXP"] + 0.627140393078931 * indata[u"GO_0042733_EXP"] + 0.975612265942266 * indata[u"GO_0048536_CSV"] + 2.50982324351973 * indata[u"MOT_2D_beta8strand_CSV"] + -1.05066350286818 * indata[u"MUT_TSSK6"] + 8.86678775920209 * indata[u"PKA_113_D"] + 6.85747444356513 * indata[u"PKA_113_D_CSV"] + -0.466956240090623 * indata[u"PKA_124_POL"] + -1.49518803669492 * indata[u"PKA_129_S"] + -7.13999974834483 * indata[u"PKA_129_S_CSV"] + -0.0791574967949416 * indata[u"PKA_129_S_EXP"] + -3.51157195973798 * indata[u"PKA_142"] + 0.069095739966826 * indata[u"PKA_164_ASA"] + 0.0313845352592106 * indata[u"PKA_271_HYD"] + -1.19631158479689 * indata[u"PKA_272_M_CSV"] + -1.95017414700034 * indata[u"PWY_R_HSA_5689880_CSV"] + -0.0681640536777008 * indata[u"PWY_R_HSA_8953750_EXP"] + 0.994481163858113 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_3 = tanh((-0.346167641793401 + -0.000358846578444729 * indata[u"DOM_Kringle_EXP"] + -1.21709605041004 * indata[u"EXP_MKNK1"] + 0.172455380923487 * indata[u"EXP_NUAK2"] + 1.55313036189727 * indata[u"EXP_TEC"] + 0.908626392349899 * indata[u"GO_0003222_CSV"] + -1.40898050114623 * indata[u"GO_0009791_CSV"] + 0.659956738189505 * indata[u"GO_0032880_EXP"] + -0.537776643506052 * indata[u"GO_0042733_EXP"] + -0.360645091798254 * indata[u"GO_0048536_CSV"] + 0.602553742955585 * indata[u"MOT_2D_beta8strand_CSV"] + -3.89834536316468 * indata[u"MUT_TSSK6"] + -3.69613991713144 * indata[u"PKA_113_D"] + -3.64436766334026 * indata[u"PKA_113_D_CSV"] + -0.034066450125474 * indata[u"PKA_124_POL"] + -0.00331292681339928 * indata[u"PKA_129_S"] + 2.9026124509602 * indata[u"PKA_129_S_CSV"] + 0.530807912870475 * indata[u"PKA_129_S_EXP"] + -2.38260448566585 * indata[u"PKA_142"] + -0.0279791112096421 * indata[u"PKA_164_ASA"] + 2.35719876857056 * indata[u"PKA_271_HYD"] + 10.9077266979345 * indata[u"PKA_272_M_CSV"] + -1.23582475960877 * indata[u"PWY_R_HSA_5689880_CSV"] + -0.270851184356333 * indata[u"PWY_R_HSA_8953750_EXP"] + 15.0932108723138 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_4 = tanh((-13.010682832923 + -0.719391677746177 * indata[u"DOM_Kringle_EXP"] + -1.63939661533638 * indata[u"EXP_MKNK1"] + 3.98758307648384 * indata[u"EXP_NUAK2"] + 1.76609598290194 * indata[u"EXP_TEC"] + 0.81371042811166 * indata[u"GO_0003222_CSV"] + -1.9513666472863 * indata[u"GO_0009791_CSV"] + -0.829956295114673 * indata[u"GO_0032880_EXP"] + -0.0424214693107946 * indata[u"GO_0042733_EXP"] + 0.865194734381644 * indata[u"GO_0048536_CSV"] + -3.01427800526445 * indata[u"MOT_2D_beta8strand_CSV"] + -6.76698794517236 * indata[u"MUT_TSSK6"] + -2.59621128123863 * indata[u"PKA_113_D"] + -2.04781916175522 * indata[u"PKA_113_D_CSV"] + 1.06972767801793 * indata[u"PKA_124_POL"] + -4.66414990869902 * indata[u"PKA_129_S"] + -5.66153307094015 * indata[u"PKA_129_S_CSV"] + -0.446764766627228 * indata[u"PKA_129_S_EXP"] + 2.11734563689132 * indata[u"PKA_142"] + -0.0923817892706903 * indata[u"PKA_164_ASA"] + 0.969037120619236 * indata[u"PKA_271_HYD"] + -24.0453732237613 * indata[u"PKA_272_M_CSV"] + -1.67387272484613 * indata[u"PWY_R_HSA_5689880_CSV"] + 0.089250747006384 * indata[u"PWY_R_HSA_8953750_EXP"] + 1.64329915416154 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_5 = tanh((-8.08244464563046 + 0.550869523655589 * indata[u"DOM_Kringle_EXP"] + 3.81306129494738 * indata[u"EXP_MKNK1"] + -0.00994433362148271 * indata[u"EXP_NUAK2"] + -2.73759963976025 * indata[u"EXP_TEC"] + 0.0873327974424508 * indata[u"GO_0003222_CSV"] + -0.0850922734691114 * indata[u"GO_0009791_CSV"] + 0.151258485046991 * indata[u"GO_0032880_EXP"] + 0.321143303415705 * indata[u"GO_0042733_EXP"] + 0.000597407953811461 * indata[u"GO_0048536_CSV"] + 1.57866502896285 * indata[u"MOT_2D_beta8strand_CSV"] + -4.46474277477633 * indata[u"MUT_TSSK6"] + -4.59348593762882 * indata[u"PKA_113_D"] + 0.694029783927386 * indata[u"PKA_113_D_CSV"] + -0.977087394190735 * indata[u"PKA_124_POL"] + -4.54604677601419 * indata[u"PKA_129_S"] + 12.2737107176076 * indata[u"PKA_129_S_CSV"] + 0.769453724493317 * indata[u"PKA_129_S_EXP"] + 0.882910368491385 * indata[u"PKA_142"] + -0.0415103695339834 * indata[u"PKA_164_ASA"] + 0.541391948203121 * indata[u"PKA_271_HYD"] + 15.1119485138667 * indata[u"PKA_272_M_CSV"] + 2.13610012620295 * indata[u"PWY_R_HSA_5689880_CSV"] + 0.478108374491184 * indata[u"PWY_R_HSA_8953750_EXP"] + -6.67829277009553 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_6 = tanh((16.6706106536609 + 0.228088868403968 * indata[u"DOM_Kringle_EXP"] + -1.71831817766033 * indata[u"EXP_MKNK1"] + -1.10958323011925 * indata[u"EXP_NUAK2"] + -2.11432401494038 * indata[u"EXP_TEC"] + 0.0887070854197045 * indata[u"GO_0003222_CSV"] + -2.11379078390431 * indata[u"GO_0009791_CSV"] + -0.274698347103587 * indata[u"GO_0032880_EXP"] + 0.37805331101688 * indata[u"GO_0042733_EXP"] + 4.78300271175443 * indata[u"GO_0048536_CSV"] + 2.12093988957494 * indata[u"MOT_2D_beta8strand_CSV"] + -1.16960886450041 * indata[u"MUT_TSSK6"] + 3.72853537012181 * indata[u"PKA_113_D"] + -0.178339298509711 * indata[u"PKA_113_D_CSV"] + -0.592782019977862 * indata[u"PKA_124_POL"] + 2.02860174295328 * indata[u"PKA_129_S"] + 2.25742949180768 * indata[u"PKA_129_S_CSV"] + 1.78246879506586 * indata[u"PKA_129_S_EXP"] + 1.62772675972697 * indata[u"PKA_142"] + 0.000495745191610731 * indata[u"PKA_164_ASA"] + -2.6829898494731 * indata[u"PKA_271_HYD"] + -11.3279176156279 * indata[u"PKA_272_M_CSV"] + 2.76649821550143 * indata[u"PWY_R_HSA_5689880_CSV"] + 0.154369534321216 * indata[u"PWY_R_HSA_8953750_EXP"] + 0.360538976256843 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_7 = tanh((-37.9194945244446 + -1.31510072339977 * indata[u"DOM_Kringle_EXP"] + 4.67072690745814 * indata[u"EXP_MKNK1"] + 1.87999266293934 * indata[u"EXP_NUAK2"] + 2.83148826792335 * indata[u"EXP_TEC"] + 0.528766852895505 * indata[u"GO_0003222_CSV"] + 0.0180906984145074 * indata[u"GO_0009791_CSV"] + 0.694513790500595 * indata[u"GO_0032880_EXP"] + 0.0806741876867824 * indata[u"GO_0042733_EXP"] + 3.43052201302476 * indata[u"GO_0048536_CSV"] + 0.848359272951055 * indata[u"MOT_2D_beta8strand_CSV"] + -2.27097844134288 * indata[u"MUT_TSSK6"] + -5.3971613063988 * indata[u"PKA_113_D"] + -3.49592728686589 * indata[u"PKA_113_D_CSV"] + 0.769354974254218 * indata[u"PKA_124_POL"] + -4.08144549767721 * indata[u"PKA_129_S"] + -0.138656726987877 * indata[u"PKA_129_S_CSV"] + -0.786404734097639 * indata[u"PKA_129_S_EXP"] + 1.99573460148078 * indata[u"PKA_142"] + 0.178129150718037 * indata[u"PKA_164_ASA"] + 0.115906119666433 * indata[u"PKA_271_HYD"] + -1.53449308435586 * indata[u"PKA_272_M_CSV"] + 1.87846194331009 * indata[u"PWY_R_HSA_5689880_CSV"] + 0.632941677457663 * indata[u"PWY_R_HSA_8953750_EXP"] + -1.21746175972017 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_8 = tanh((-9.49114927165583 + -0.473919696297717 * indata[u"DOM_Kringle_EXP"] + 1.59690564980831 * indata[u"EXP_MKNK1"] + 0.299737981994394 * indata[u"EXP_NUAK2"] + -0.26952809843397 * indata[u"EXP_TEC"] + 3.78697972876595 * indata[u"GO_0003222_CSV"] + 1.32689576535556 * indata[u"GO_0009791_CSV"] + 0.746547484006345 * indata[u"GO_0032880_EXP"] + -0.200712502200203 * indata[u"GO_0042733_EXP"] + 3.41854817593668 * indata[u"GO_0048536_CSV"] + -0.244178694182013 * indata[u"MOT_2D_beta8strand_CSV"] + -1.60407859594169 * indata[u"MUT_TSSK6"] + 4.67887131558885 * indata[u"PKA_113_D"] + 0.0136908189877722 * indata[u"PKA_113_D_CSV"] + -0.464059315752434 * indata[u"PKA_124_POL"] + 4.34493552957081 * indata[u"PKA_129_S"] + 2.39386350809367 * indata[u"PKA_129_S_CSV"] + 0.576611467986752 * indata[u"PKA_129_S_EXP"] + -0.276797427253007 * indata[u"PKA_142"] + 0.114730092770265 * indata[u"PKA_164_ASA"] + 1.16850282203506 * indata[u"PKA_271_HYD"] + -14.0006791795262 * indata[u"PKA_272_M_CSV"] + 3.79503929884159 * indata[u"PWY_R_HSA_5689880_CSV"] + 0.304465543597653 * indata[u"PWY_R_HSA_8953750_EXP"] + -1.10110476532794 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_9 = tanh((39.0155459405502 + 1.47974203233463 * indata[u"DOM_Kringle_EXP"] + -0.957864893475404 * indata[u"EXP_MKNK1"] + -9.32730910705165 * indata[u"EXP_NUAK2"] + -0.559727852646627 * indata[u"EXP_TEC"] + -1.49965697795193 * indata[u"GO_0003222_CSV"] + 3.8753109969648 * indata[u"GO_0009791_CSV"] + 0.84129080495271 * indata[u"GO_0032880_EXP"] + 0.946255607146667 * indata[u"GO_0042733_EXP"] + 1.61343419490344 * indata[u"GO_0048536_CSV"] + 5.15289667870701 * indata[u"MOT_2D_beta8strand_CSV"] + 1.28536511859912 * indata[u"MUT_TSSK6"] + 2.17442503457136 * indata[u"PKA_113_D"] + -12.3766658431035 * indata[u"PKA_113_D_CSV"] + -1.26073674069199 * indata[u"PKA_124_POL"] + 2.38656018673085 * indata[u"PKA_129_S"] + 6.00290251604017 * indata[u"PKA_129_S_CSV"] + -0.345571740404031 * indata[u"PKA_129_S_EXP"] + -0.508905846271911 * indata[u"PKA_142"] + 0.224933728089171 * indata[u"PKA_164_ASA"] + -8.92954572262413 * indata[u"PKA_271_HYD"] + 1.62690716375687 * indata[u"PKA_272_M_CSV"] + -2.88825711234613 * indata[u"PWY_R_HSA_5689880_CSV"] + 0.511356251768311 * indata[u"PWY_R_HSA_8953750_EXP"] + 5.60004404705908 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_10 = tanh((-22.926094864276 + 0.433314325048857 * indata[u"DOM_Kringle_EXP"] + 0.825370151353752 * indata[u"EXP_MKNK1"] + -0.243256769196492 * indata[u"EXP_NUAK2"] + 5.91723613062521 * indata[u"EXP_TEC"] + 0.621836579190898 * indata[u"GO_0003222_CSV"] + -0.995501976320629 * indata[u"GO_0009791_CSV"] + -0.684806246933919 * indata[u"GO_0032880_EXP"] + -0.33109917817283 * indata[u"GO_0042733_EXP"] + -1.9712936154548 * indata[u"GO_0048536_CSV"] + -1.46458864836509 * indata[u"MOT_2D_beta8strand_CSV"] + 1.04480047951964 * indata[u"MUT_TSSK6"] + -3.95391522967647 * indata[u"PKA_113_D"] + 5.50887385891888 * indata[u"PKA_113_D_CSV"] + 0.429198528864883 * indata[u"PKA_124_POL"] + 0.0239676961826682 * indata[u"PKA_129_S"] + 0.148178617005496 * indata[u"PKA_129_S_CSV"] + 0.363298691604644 * indata[u"PKA_129_S_EXP"] + 0.171569979957445 * indata[u"PKA_142"] + 0.079167747991437 * indata[u"PKA_164_ASA"] + -7.36277685898467 * indata[u"PKA_271_HYD"] + -5.12155025038367 * indata[u"PKA_272_M_CSV"] + 0.504998190229338 * indata[u"PWY_R_HSA_5689880_CSV"] + 0.13722028384716 * indata[u"PWY_R_HSA_8953750_EXP"] + 6.40138889801382 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_11 = tanh((5.03246866366221 + 0.167286732057405 * indata[u"DOM_Kringle_EXP"] + 6.05495568497851 * indata[u"EXP_MKNK1"] + 1.40610442597946 * indata[u"EXP_NUAK2"] + -9.914342110151 * indata[u"EXP_TEC"] + 0.698655536622627 * indata[u"GO_0003222_CSV"] + 2.37948949715347 * indata[u"GO_0009791_CSV"] + -0.187559356886146 * indata[u"GO_0032880_EXP"] + -0.127399165061022 * indata[u"GO_0042733_EXP"] + 2.83704827198768 * indata[u"GO_0048536_CSV"] + 1.03632979178205 * indata[u"MOT_2D_beta8strand_CSV"] + 0.505566056490075 * indata[u"MUT_TSSK6"] + 0.181337300085476 * indata[u"PKA_113_D"] + -5.86684476573449 * indata[u"PKA_113_D_CSV"] + -0.108430328890692 * indata[u"PKA_124_POL"] + 2.60090993095511 * indata[u"PKA_129_S"] + 3.7154816673975 * indata[u"PKA_129_S_CSV"] + 0.475284435659079 * indata[u"PKA_129_S_EXP"] + -0.378466658558173 * indata[u"PKA_142"] + 0.0279186621439135 * indata[u"PKA_164_ASA"] + 0.978377616451713 * indata[u"PKA_271_HYD"] + 4.10654963996786 * indata[u"PKA_272_M_CSV"] + 1.77450505807488 * indata[u"PWY_R_HSA_5689880_CSV"] + -0.0783224939717815 * indata[u"PWY_R_HSA_8953750_EXP"] + 4.0765930837473 * indata[u"REC_R_HSA_2984220_CSV"]))

    H1_12 = tanh((-12.151126669546 + -0.735837275512198 * indata[u"DOM_Kringle_EXP"] + 1.75137114402906 * indata[u"EXP_MKNK1"] + 2.02129338586413 * indata[u"EXP_NUAK2"] + -0.546441523322612 * indata[u"EXP_TEC"] + 0.529375737127279 * indata[u"GO_0003222_CSV"] + -3.43768334925504 * indata[u"GO_0009791_CSV"] + -0.411191971443252 * indata[u"GO_0032880_EXP"] + -0.210955840928912 * indata[u"GO_0042733_EXP"] + 4.11231776599256 * indata[u"GO_0048536_CSV"] + 0.862023148803887 * indata[u"MOT_2D_beta8strand_CSV"] + 0.862532382726247 * indata[u"MUT_TSSK6"] + -0.808039451090211 * indata[u"PKA_113_D"] + -3.73326123846922 * indata[u"PKA_113_D_CSV"] + -1.26260874926794 * indata[u"PKA_124_POL"] + -6.89179366258018 * indata[u"PKA_129_S"] + -2.2841739833468 * indata[u"PKA_129_S_CSV"] + 1.08856862771735 * indata[u"PKA_129_S_EXP"] + -1.12731782966687 * indata[u"PKA_142"] + -0.0236616989567648 * indata[u"PKA_164_ASA"] + 8.58536628299591 * indata[u"PKA_271_HYD"] + 0.57753514002797 * indata[u"PKA_272_M_CSV"] + -1.10302328674309 * indata[u"PWY_R_HSA_5689880_CSV"] + 0.273320540612883 * indata[u"PWY_R_HSA_8953750_EXP"] + 0.422806465202048 * indata[u"REC_R_HSA_2984220_CSV"]))

    outdata[u"Predicted IC50_1"] = 3.06101365536316 + 0.000981933194975131 * H1_1 + 0.376048465836012 * H1_10 + -0.09896056462635 * H1_11 + -0.61889139737651 * H1_12 + -0.314817317670535 * H1_2 + 0.846961341681091 * H1_3 + -0.715353322065404 * H1_4 + 0.296136431365031 * H1_5 + 0.964133680394354 * H1_6 + 0.722437205838172 * H1_7 + -0.77415144135517 * H1_8 + -1.10211520497264 * H1_9

    return outdata[u"Predicted IC50_1"]


