from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """

def getModelMetadata():
	return {"creator": u"Neural", "modelName": u"", "predicted": u"IC50", "table": u"upper_aerodigestive_tract", "version": u"14.1.0", "timestamp": u"2019-08-06T02:59:55Z"}


def getInputMetadata():
    return {
        u"EXP_LIMK2": "float",
        u"EXP_MINK1": "float",
        u"EXP_ROCK1": "float",
        u"EXP_WNK4": "float",
        u"GO_0001649": "float",
        u"GO_0001649_EXP": "float",
        u"GO_0016477_CSV": "float",
        u"GO_0019722_CSV": "float",
        u"GO_0030154": "float",
        u"GO_0045765_EXP": "float",
        u"GO_2001240": "float",
        u"PKA_153_CHA": "float",
        u"REC_R_HSA_194922": "float",
        u"SFAM_Csk": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6
    # H1_7
    # H1_8
    # H1_9
    # H1_10
    # H1_11
    # H1_12

    H1_1 = tanh((-25.5579958462944 + 0.917232725220927 * indata[u"EXP_LIMK2"] + -3.73292553143261 * indata[u"EXP_MINK1"] + 6.09693378856033 * indata[u"EXP_ROCK1"] + 6.02380974368412 * indata[u"EXP_WNK4"] + -0.0231444722325352 * indata[u"GO_0001649"] + 0.562526436938887 * indata[u"GO_0001649_EXP"] + -0.964492136728845 * indata[u"GO_0016477_CSV"] + 5.69959515664606 * indata[u"GO_0019722_CSV"] + -1.15349371270666 * indata[u"GO_0030154"] + -0.73141482885313 * indata[u"GO_0045765_EXP"] + 2.49536682690475 * indata[u"GO_2001240"] + -150.294295459237 * indata[u"PKA_153_CHA"] + 3.14711166464819 * indata[u"REC_R_HSA_194922"] + -0.39647245468418 * indata[u"SFAM_Csk"]))

    H1_2 = tanh((66.7900279953133 + -0.484443142979105 * indata[u"EXP_LIMK2"] + -4.7166245226954 * indata[u"EXP_MINK1"] + -6.4340172236323 * indata[u"EXP_ROCK1"] + -6.98383904345028 * indata[u"EXP_WNK4"] + 0.0775563771058029 * indata[u"GO_0001649"] + 0.839347696942186 * indata[u"GO_0001649_EXP"] + -0.456844100569835 * indata[u"GO_0016477_CSV"] + -2.24817144487705 * indata[u"GO_0019722_CSV"] + 0.922001839579402 * indata[u"GO_0030154"] + 0.568385139441378 * indata[u"GO_0045765_EXP"] + -4.65614230701233 * indata[u"GO_2001240"] + 2.17679424368521 * indata[u"PKA_153_CHA"] + -1.56334883785887 * indata[u"REC_R_HSA_194922"] + 0.554352881227559 * indata[u"SFAM_Csk"]))

    H1_3 = tanh((-12.1820958912332 + 0.69718620738018 * indata[u"EXP_LIMK2"] + 3.62092574962761 * indata[u"EXP_MINK1"] + -5.7361408400673 * indata[u"EXP_ROCK1"] + 3.2829864483729 * indata[u"EXP_WNK4"] + 1.57005520046665 * indata[u"GO_0001649"] + 0.184056056863667 * indata[u"GO_0001649_EXP"] + -0.757021838819256 * indata[u"GO_0016477_CSV"] + -1.57235661202294 * indata[u"GO_0019722_CSV"] + 0.373611316096315 * indata[u"GO_0030154"] + 0.0583864626619893 * indata[u"GO_0045765_EXP"] + 2.29863228387301 * indata[u"GO_2001240"] + 1.483056623257 * indata[u"PKA_153_CHA"] + -2.5107854886964 * indata[u"REC_R_HSA_194922"] + -0.473089680390556 * indata[u"SFAM_Csk"]))

    H1_4 = tanh((5.19470271802352 + 0.395325896381491 * indata[u"EXP_LIMK2"] + -3.4768769887205 * indata[u"EXP_MINK1"] + 0.126015509422284 * indata[u"EXP_ROCK1"] + 2.62674276940074 * indata[u"EXP_WNK4"] + 0.85122642150742 * indata[u"GO_0001649"] + -0.264926730054735 * indata[u"GO_0001649_EXP"] + -0.192405712736664 * indata[u"GO_0016477_CSV"] + 4.34107612874479 * indata[u"GO_0019722_CSV"] + -1.60576806824656 * indata[u"GO_0030154"] + 0.246515422339767 * indata[u"GO_0045765_EXP"] + 0.13027494511909 * indata[u"GO_2001240"] + 2.65494547034018 * indata[u"PKA_153_CHA"] + -1.3906217775127 * indata[u"REC_R_HSA_194922"] + 2.00520124651906 * indata[u"SFAM_Csk"]))

    H1_5 = tanh((28.114690105365 + 0.503458109895364 * indata[u"EXP_LIMK2"] + -0.43036599602381 * indata[u"EXP_MINK1"] + 2.81113122588025 * indata[u"EXP_ROCK1"] + -11.9065409267609 * indata[u"EXP_WNK4"] + -4.85410546032291 * indata[u"GO_0001649"] + 0.109260873254258 * indata[u"GO_0001649_EXP"] + -3.05569735180433 * indata[u"GO_0016477_CSV"] + 3.15391053256143 * indata[u"GO_0019722_CSV"] + -0.308961097067692 * indata[u"GO_0030154"] + 0.0683662469757361 * indata[u"GO_0045765_EXP"] + -1.37233804949377 * indata[u"GO_2001240"] + 2.77237266577253 * indata[u"PKA_153_CHA"] + 1.99807715247301 * indata[u"REC_R_HSA_194922"] + 2.13956483287083 * indata[u"SFAM_Csk"]))

    H1_6 = tanh((-33.6889476181595 + -0.171764683799278 * indata[u"EXP_LIMK2"] + 2.56943856190348 * indata[u"EXP_MINK1"] + -0.179893829847122 * indata[u"EXP_ROCK1"] + 7.26870112903617 * indata[u"EXP_WNK4"] + 3.44208306449781 * indata[u"GO_0001649"] + 0.469925880726343 * indata[u"GO_0001649_EXP"] + -0.316481025282772 * indata[u"GO_0016477_CSV"] + 1.41861868125833 * indata[u"GO_0019722_CSV"] + 0.564156353532372 * indata[u"GO_0030154"] + 0.144951035820547 * indata[u"GO_0045765_EXP"] + 3.06370446884268 * indata[u"GO_2001240"] + -2.25181301461919 * indata[u"PKA_153_CHA"] + 3.06698093021798 * indata[u"REC_R_HSA_194922"] + -1.28039599805285 * indata[u"SFAM_Csk"]))

    H1_7 = tanh((28.597781171751 + 0.503540398130431 * indata[u"EXP_LIMK2"] + -1.72303374609741 * indata[u"EXP_MINK1"] + -1.68227802516937 * indata[u"EXP_ROCK1"] + -5.50782570696244 * indata[u"EXP_WNK4"] + -7.44918304813284 * indata[u"GO_0001649"] + -0.3706101628068 * indata[u"GO_0001649_EXP"] + 1.33507002539548 * indata[u"GO_0016477_CSV"] + -0.618246898757288 * indata[u"GO_0019722_CSV"] + -0.244206598872294 * indata[u"GO_0030154"] + -0.37492364830472 * indata[u"GO_0045765_EXP"] + -0.629879499125553 * indata[u"GO_2001240"] + 2.80236328733383 * indata[u"PKA_153_CHA"] + 2.45781020167828 * indata[u"REC_R_HSA_194922"] + 1.58235660755543 * indata[u"SFAM_Csk"]))

    H1_8 = tanh((8.77243910462019 + -0.0229936437095216 * indata[u"EXP_LIMK2"] + -0.270146390929661 * indata[u"EXP_MINK1"] + -1.34758759917139 * indata[u"EXP_ROCK1"] + -1.02522551730577 * indata[u"EXP_WNK4"] + -2.10312290713154 * indata[u"GO_0001649"] + -0.981601730025739 * indata[u"GO_0001649_EXP"] + 1.2920843058331 * indata[u"GO_0016477_CSV"] + -1.84632609819254 * indata[u"GO_0019722_CSV"] + 0.538975131374766 * indata[u"GO_0030154"] + -0.531718941310938 * indata[u"GO_0045765_EXP"] + -1.38673696768472 * indata[u"GO_2001240"] + -1.44674593069829 * indata[u"PKA_153_CHA"] + 3.21948160307973 * indata[u"REC_R_HSA_194922"] + -2.14032656004694 * indata[u"SFAM_Csk"]))

    H1_9 = tanh((-14.4655355326085 + 0.205267461027677 * indata[u"EXP_LIMK2"] + 2.95757054586998 * indata[u"EXP_MINK1"] + -0.623773492698766 * indata[u"EXP_ROCK1"] + 0.844438491912286 * indata[u"EXP_WNK4"] + 0.510130792143189 * indata[u"GO_0001649"] + -0.363587700183688 * indata[u"GO_0001649_EXP"] + -1.03715030471248 * indata[u"GO_0016477_CSV"] + 1.28759289296338 * indata[u"GO_0019722_CSV"] + -0.00764550005778828 * indata[u"GO_0030154"] + 0.648680198165674 * indata[u"GO_0045765_EXP"] + 1.25738514547071 * indata[u"GO_2001240"] + -1.89939627907496 * indata[u"PKA_153_CHA"] + -0.274693064826665 * indata[u"REC_R_HSA_194922"] + -1.70008690068901 * indata[u"SFAM_Csk"]))

    H1_10 = tanh((13.4676966671127 + 0.433059508508823 * indata[u"EXP_LIMK2"] + 1.56219526686113 * indata[u"EXP_MINK1"] + -2.11302719091077 * indata[u"EXP_ROCK1"] + -5.64931986228649 * indata[u"EXP_WNK4"] + 0.735494912953148 * indata[u"GO_0001649"] + 0.807026180769286 * indata[u"GO_0001649_EXP"] + -0.543815800210997 * indata[u"GO_0016477_CSV"] + -2.57105348498404 * indata[u"GO_0019722_CSV"] + 0.164292837302092 * indata[u"GO_0030154"] + -0.370219916810621 * indata[u"GO_0045765_EXP"] + -1.66149872487775 * indata[u"GO_2001240"] + -0.224081653543464 * indata[u"PKA_153_CHA"] + -3.40188574825145 * indata[u"REC_R_HSA_194922"] + 2.72111944485297 * indata[u"SFAM_Csk"]))

    H1_11 = tanh((-25.6876121599471 + -0.183782917294442 * indata[u"EXP_LIMK2"] + 1.85397605877237 * indata[u"EXP_MINK1"] + 1.16427884914428 * indata[u"EXP_ROCK1"] + 4.81448708541283 * indata[u"EXP_WNK4"] + -2.54566855850138 * indata[u"GO_0001649"] + 0.133031580331757 * indata[u"GO_0001649_EXP"] + 0.58802351131952 * indata[u"GO_0016477_CSV"] + 0.325049031631941 * indata[u"GO_0019722_CSV"] + -0.138158670524213 * indata[u"GO_0030154"] + -0.730162286608989 * indata[u"GO_0045765_EXP"] + 3.20280193934841 * indata[u"GO_2001240"] + -1.98080699422255 * indata[u"PKA_153_CHA"] + -2.5597165152561 * indata[u"REC_R_HSA_194922"] + 4.70366947050943 * indata[u"SFAM_Csk"]))

    H1_12 = tanh((45.4682796392555 + 0.322637508514129 * indata[u"EXP_LIMK2"] + -3.87081319073831 * indata[u"EXP_MINK1"] + -3.82251296317685 * indata[u"EXP_ROCK1"] + -5.01396080073108 * indata[u"EXP_WNK4"] + 2.91537519813609 * indata[u"GO_0001649"] + -0.139788559135372 * indata[u"GO_0001649_EXP"] + -2.31187421374032 * indata[u"GO_0016477_CSV"] + -0.729385108100093 * indata[u"GO_0019722_CSV"] + 0.390315118907019 * indata[u"GO_0030154"] + -0.121709960625171 * indata[u"GO_0045765_EXP"] + -3.88523554290276 * indata[u"GO_2001240"] + 0.282677429143542 * indata[u"PKA_153_CHA"] + 0.789190021763598 * indata[u"REC_R_HSA_194922"] + -0.54109708197934 * indata[u"SFAM_Csk"]))

    outdata[u"Predicted IC50_1"] = 2.16540077785481 + 0.986674296211045 * H1_1 + -0.690563921815522 * H1_10 + -0.058367463305592 * H1_11 + -0.876325018959187 * H1_12 + 1.13410138194591 * H1_2 + 0.692043201844697 * H1_3 + -0.847132753114359 * H1_4 + 1.10103410728962 * H1_5 + 0.101033190588968 * H1_6 + -0.235639156313831 * H1_7 + 0.0300846122256456 * H1_8 + -0.577252788163344 * H1_9

    return outdata[u"Predicted IC50_1"]


