library(glmnet)
mydata = read.table("./TrainingSet/ReliefF/soft_tissue.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=0.75,family="gaussian",standardize=TRUE)
sink('./Model/EN/ReliefF/soft_tissue/soft_tissue_077.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
