library(glmnet)
mydata = read.table("./TrainingSet/AvgRank/NSCLC.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=0.65,family="gaussian",standardize=TRUE)
sink('./Model/EN/AvgRank/NSCLC/NSCLC_069.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
