library(glmnet)
mydata = read.table("./TrainingSet/ReliefF/lymphoid.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0.9,family="gaussian",standardize=FALSE)
sink('./Model/EN/ReliefF/lymphoid/lymphoid_092.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
