library(glmnet)
mydata = read.table("./TrainingSet/RF/large_intestine.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=0.7,family="gaussian",standardize=TRUE)
sink('./Model/EN/Classifier/large_intestine/large_intestine_073.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
