library(glmnet)
mydata = read.table("./TrainingSet/RF/large_intestine.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0.1,family="gaussian",standardize=FALSE)
sink('./Model/EN/Classifier/large_intestine/large_intestine_028.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
