library(glmnet)
mydata = read.table("./TrainingSet/Correlation/large_intestine.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mae",alpha=0.55,family="gaussian",standardize=TRUE)
sink('./Model/EN/Correlation/large_intestine/large_intestine_063.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
