from __future__ import division
import jmp_score as jmp
from math import *
import numpy as np


""" ==================================================================
 Copyright(C) 2018 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation. Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS. SAS and all other SAS
 Institute Inc. product and service names are registered
 trademarks or trademarks of SAS Institute Inc. in the USA
 and other countries. Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v14.1.0 """

def getModelMetadata():
	return {"creator": u"Neural", "modelName": u"", "predicted": u"IC50", "table": u"upper_aerodigestive_tract", "version": u"14.1.0", "timestamp": u"2020-09-21T20:38:10Z"}


def getInputMetadata():
    return {
        u"EXP_ANKK1": "float",
        u"EXP_FAM198B": "float",
        u"EXP_LIMK2": "float",
        u"EXP_MINK1": "float",
        u"EXP_ROCK1": "float",
        u"EXP_WNK4": "float",
        u"GO_0007257_CSV": "float",
        u"GO_0014068_CSV": "float",
        u"GO_0016477_CSV": "float",
        u"GO_0045765_EXP": "float",
        u"GO_2001240": "float",
        u"MOT_2D_linker_CSV": "float",
        u"PKA_153_CHA": "float",
        u"PWY_R_HSA_8848021_EXP": "float",
        u"SFAM_Alpha_Unclassified_EXP": "float"
	}


def getOutputMetadata():
    return {
        u"Predicted IC50_1": "float"
	}


def score(indata, outdata):
    # H1_1
    # H1_2
    # H1_3
    # H1_4
    # H1_5
    # H1_6
    # H1_7
    # H1_8
    # H1_9
    # H1_10
    # H1_11
    # H1_12

    H1_1 = tanh((-1.26208908502014 + 0.15241667812067 * indata[u"EXP_ANKK1"] + 0.0260807627417395 * indata[u"EXP_FAM198B"] + -0.000257102954394112 * indata[u"EXP_LIMK2"] + -0.00224236145307638 * indata[u"EXP_MINK1"] + 0.502843390660551 * indata[u"EXP_ROCK1"] + -0.405377126455797 * indata[u"EXP_WNK4"] + -0.914214876853765 * indata[u"GO_0007257_CSV"] + 0.00114437741120346 * indata[u"GO_0014068_CSV"] + 0.000247756028829154 * indata[u"GO_0016477_CSV"] + -0.000388017607642302 * indata[u"GO_0045765_EXP"] + 0.244195237279036 * indata[u"GO_2001240"] + -0.00108429458755439 * indata[u"MOT_2D_linker_CSV"] + 0.0022535098139782 * indata[u"PKA_153_CHA"] + 0.000195964865635883 * indata[u"PWY_R_HSA_8848021_EXP"] + -0.000371893097101884 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_2 = tanh((13.2442158566591 + 0.12295953033208 * indata[u"EXP_ANKK1"] + 0.252859754826779 * indata[u"EXP_FAM198B"] + -0.458537078539205 * indata[u"EXP_LIMK2"] + 0.0736137465986891 * indata[u"EXP_MINK1"] + -1.14002909997856 * indata[u"EXP_ROCK1"] + -2.66630284494548 * indata[u"EXP_WNK4"] + 0.411167479726785 * indata[u"GO_0007257_CSV"] + -0.832814142675398 * indata[u"GO_0014068_CSV"] + -0.0464747531349361 * indata[u"GO_0016477_CSV"] + -0.389355028630075 * indata[u"GO_0045765_EXP"] + -0.971191481414654 * indata[u"GO_2001240"] + 0.793328558431388 * indata[u"MOT_2D_linker_CSV"] + 0.389239730228739 * indata[u"PKA_153_CHA"] + 0.203472300137675 * indata[u"PWY_R_HSA_8848021_EXP"] + 0.0000620701984487071 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_3 = tanh((-2.06420952137227 + 0.000958451808696441 * indata[u"EXP_ANKK1"] + 0.00047376911310035 * indata[u"EXP_FAM198B"] + -0.000183227642646107 * indata[u"EXP_LIMK2"] + 0.103017380425443 * indata[u"EXP_MINK1"] + -0.550160556995612 * indata[u"EXP_ROCK1"] + 1.11709434304502 * indata[u"EXP_WNK4"] + -0.193989636303525 * indata[u"GO_0007257_CSV"] + 0.0000241087288982269 * indata[u"GO_0014068_CSV"] + -0.00134507957489604 * indata[u"GO_0016477_CSV"] + -0.000368796372322173 * indata[u"GO_0045765_EXP"] + 0.0000500604148138857 * indata[u"GO_2001240"] + 0.00309700599938021 * indata[u"MOT_2D_linker_CSV"] + -0.00107148608540703 * indata[u"PKA_153_CHA"] + -0.000952212348368656 * indata[u"PWY_R_HSA_8848021_EXP"] + -0.000221461505786622 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_4 = tanh((-0.111854441912868 + -0.00332729518725137 * indata[u"EXP_ANKK1"] + -0.0000631510680268621 * indata[u"EXP_FAM198B"] + 0.0000251209248980991 * indata[u"EXP_LIMK2"] + -0.000893311574976383 * indata[u"EXP_MINK1"] + 0.000164031664535064 * indata[u"EXP_ROCK1"] + 0.00385066304616862 * indata[u"EXP_WNK4"] + 0.0024214017492322 * indata[u"GO_0007257_CSV"] + 0.00133274022195965 * indata[u"GO_0014068_CSV"] + 0.796611957885587 * indata[u"GO_0016477_CSV"] + -0.000474980869692302 * indata[u"GO_0045765_EXP"] + 0.000542041109867916 * indata[u"GO_2001240"] + -0.00354940808436416 * indata[u"MOT_2D_linker_CSV"] + 0.000419244042080045 * indata[u"PKA_153_CHA"] + -0.024717937524181 * indata[u"PWY_R_HSA_8848021_EXP"] + -0.000361114840240514 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_5 = tanh((-1.33105360556005 + -0.00216953446098142 * indata[u"EXP_ANKK1"] + 0.000559464132728518 * indata[u"EXP_FAM198B"] + 0.162838072257397 * indata[u"EXP_LIMK2"] + 0.00041832885770287 * indata[u"EXP_MINK1"] + 0.00301081449333353 * indata[u"EXP_ROCK1"] + -0.00353088418670755 * indata[u"EXP_WNK4"] + -0.152098350153893 * indata[u"GO_0007257_CSV"] + 0.23550983282086 * indata[u"GO_0014068_CSV"] + 0.000202645758308698 * indata[u"GO_0016477_CSV"] + 0.0947951214084325 * indata[u"GO_0045765_EXP"] + 0.00269846869357985 * indata[u"GO_2001240"] + 0.00294133231354067 * indata[u"MOT_2D_linker_CSV"] + 0.509376865753926 * indata[u"PKA_153_CHA"] + 0.000477432965111453 * indata[u"PWY_R_HSA_8848021_EXP"] + 0.0652092546698751 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_6 = tanh((0.0518604125751643 + 0.0000648368453585555 * indata[u"EXP_ANKK1"] + 0.000120909678025138 * indata[u"EXP_FAM198B"] + -0.000582177431653785 * indata[u"EXP_LIMK2"] + -0.00172731712994352 * indata[u"EXP_MINK1"] + -0.00394989472302301 * indata[u"EXP_ROCK1"] + -0.00467112841926297 * indata[u"EXP_WNK4"] + -0.245146341587714 * indata[u"GO_0007257_CSV"] + -0.00332231078485092 * indata[u"GO_0014068_CSV"] + 0.000871049529689939 * indata[u"GO_0016477_CSV"] + 0.0244004523743885 * indata[u"GO_0045765_EXP"] + -0.000542560557536847 * indata[u"GO_2001240"] + -0.00300751124174576 * indata[u"MOT_2D_linker_CSV"] + 0.00160609085869319 * indata[u"PKA_153_CHA"] + -0.000121892389720834 * indata[u"PWY_R_HSA_8848021_EXP"] + 0.000229029254980675 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_7 = tanh((0.0287939057326739 + 0.00107726177427512 * indata[u"EXP_ANKK1"] + 0.00011599345174704 * indata[u"EXP_FAM198B"] + -0.000286645375908822 * indata[u"EXP_LIMK2"] + -0.000514346744920857 * indata[u"EXP_MINK1"] + -0.00141468159570314 * indata[u"EXP_ROCK1"] + -0.020562880556601 * indata[u"EXP_WNK4"] + -0.126887219021367 * indata[u"GO_0007257_CSV"] + 0.415785622611384 * indata[u"GO_0014068_CSV"] + 0.000288473974419735 * indata[u"GO_0016477_CSV"] + 0.0772144594761006 * indata[u"GO_0045765_EXP"] + 0.0000728764636160955 * indata[u"GO_2001240"] + -0.000855987612470601 * indata[u"MOT_2D_linker_CSV"] + -0.00124660248850135 * indata[u"PKA_153_CHA"] + 0.000240845038359686 * indata[u"PWY_R_HSA_8848021_EXP"] + -0.000202468223792178 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_8 = tanh((1.46492607650185 + -0.00325708297842585 * indata[u"EXP_ANKK1"] + 0.00035218844271442 * indata[u"EXP_FAM198B"] + -0.234964854752347 * indata[u"EXP_LIMK2"] + -0.00167221069035394 * indata[u"EXP_MINK1"] + 0.00112044067783452 * indata[u"EXP_ROCK1"] + -0.000871798076978593 * indata[u"EXP_WNK4"] + 0.202107583940899 * indata[u"GO_0007257_CSV"] + -0.00116393933561677 * indata[u"GO_0014068_CSV"] + -0.600424332337972 * indata[u"GO_0016477_CSV"] + 0.000299215817220889 * indata[u"GO_0045765_EXP"] + 0.000567473474284328 * indata[u"GO_2001240"] + 0.00318201652374656 * indata[u"MOT_2D_linker_CSV"] + -0.000620152643477207 * indata[u"PKA_153_CHA"] + -0.0000530381686117881 * indata[u"PWY_R_HSA_8848021_EXP"] + -0.0670808377929746 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_9 = tanh((9.6903015255908 + -0.0000971721862090348 * indata[u"EXP_ANKK1"] + 0.101406055889608 * indata[u"EXP_FAM198B"] + 0.00038684539095084 * indata[u"EXP_LIMK2"] + -2.15047549027692 * indata[u"EXP_MINK1"] + 0.00010362593250795 * indata[u"EXP_ROCK1"] + -0.0042423182417202 * indata[u"EXP_WNK4"] + -0.184525984219085 * indata[u"GO_0007257_CSV"] + 0.00356226084027538 * indata[u"GO_0014068_CSV"] + 0.000567900658009594 * indata[u"GO_0016477_CSV"] + -0.146174272533424 * indata[u"GO_0045765_EXP"] + -0.000301766966291704 * indata[u"GO_2001240"] + -0.00221791527361628 * indata[u"MOT_2D_linker_CSV"] + 0.00104094728826128 * indata[u"PKA_153_CHA"] + -0.00808307356889343 * indata[u"PWY_R_HSA_8848021_EXP"] + -0.0228079953138783 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_10 = tanh((14.5195724440521 + -0.431329125360639 * indata[u"EXP_ANKK1"] + 0.307574257142972 * indata[u"EXP_FAM198B"] + -0.0412616941227979 * indata[u"EXP_LIMK2"] + -0.133727183465307 * indata[u"EXP_MINK1"] + -0.123903308512467 * indata[u"EXP_ROCK1"] + -4.30267443932589 * indata[u"EXP_WNK4"] + -0.232774596944678 * indata[u"GO_0007257_CSV"] + -0.565885226074197 * indata[u"GO_0014068_CSV"] + 0.159119320560152 * indata[u"GO_0016477_CSV"] + 0.000468908761886964 * indata[u"GO_0045765_EXP"] + 0.00425036859199556 * indata[u"GO_2001240"] + -0.0000905285142585808 * indata[u"MOT_2D_linker_CSV"] + 0.418550844427631 * indata[u"PKA_153_CHA"] + 0.0208276759534905 * indata[u"PWY_R_HSA_8848021_EXP"] + -0.0058978461504723 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_11 = tanh((-0.164008731279685 + -0.00023377723347552 * indata[u"EXP_ANKK1"] + -0.000585921521344907 * indata[u"EXP_FAM198B"] + -0.000196295916707021 * indata[u"EXP_LIMK2"] + 0.00152228981301829 * indata[u"EXP_MINK1"] + -0.0013024204787073 * indata[u"EXP_ROCK1"] + 0.0525642151236871 * indata[u"EXP_WNK4"] + 0.00266714460016142 * indata[u"GO_0007257_CSV"] + -0.00262929654521151 * indata[u"GO_0014068_CSV"] + -0.00190809878146764 * indata[u"GO_0016477_CSV"] + -0.000328543222168892 * indata[u"GO_0045765_EXP"] + 0.0551223873813856 * indata[u"GO_2001240"] + 0.00409560312664713 * indata[u"MOT_2D_linker_CSV"] + 0.000985574826582677 * indata[u"PKA_153_CHA"] + -0.000031835270384579 * indata[u"PWY_R_HSA_8848021_EXP"] + 0.000117434335546307 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    H1_12 = tanh((-0.00939774892658214 + 0.00276922066233826 * indata[u"EXP_ANKK1"] + 0.000519514095615249 * indata[u"EXP_FAM198B"] + -0.000465851082117358 * indata[u"EXP_LIMK2"] + 0.000796766541219155 * indata[u"EXP_MINK1"] + -0.00265741243763251 * indata[u"EXP_ROCK1"] + -0.00281020492795072 * indata[u"EXP_WNK4"] + 0.00243412946806791 * indata[u"GO_0007257_CSV"] + -0.0271847966433085 * indata[u"GO_0014068_CSV"] + 0.000409257787210118 * indata[u"GO_0016477_CSV"] + 0.000332426790862941 * indata[u"GO_0045765_EXP"] + 0.001740664447448 * indata[u"GO_2001240"] + -0.00384159169251775 * indata[u"MOT_2D_linker_CSV"] + -0.00233710524437338 * indata[u"PKA_153_CHA"] + 0.0262631956497368 * indata[u"PWY_R_HSA_8848021_EXP"] + -0.000868193624264729 * indata[u"SFAM_Alpha_Unclassified_EXP"]))

    outdata[u"Predicted IC50_1"] = 2.40859230821356 + -0.445400784264452 * H1_1 + 0.98725024158793 * H1_10 + -1.20844119959745 * H1_11 + 1.01487499282642 * H1_12 + -1.04241888353221 * H1_2 + 0.465517871249184 * H1_3 + -0.248095624421352 * H1_4 + -0.830370937433512 * H1_5 + -0.993991131999259 * H1_6 + -0.63882294338053 * H1_7 + 0.659664236280752 * H1_8 + 0.206611292831274 * H1_9

    return outdata[u"Predicted IC50_1"]


