library(glmnet)
mydata = read.table("./TrainingSet/LassoBIC/pleura.csv",head=T,sep=",")
x = as.matrix(mydata[,4:ncol(mydata)])
y = as.matrix(mydata[,1])
set.seed(123)
glm = cv.glmnet(x,y,nfolds=10,type.measure="mse",alpha=1,family="gaussian",standardize=TRUE)
sink('./Model/EN/Lasso/pleura/pleura_097.txt',append=TRUE)
print(glm$glmnet.fit)
sink()
